#!/usr/bin/env bash

#
#   Copyright 2025 Kompile Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
#

# Source file.
src="$(printf %q "$1")"
shift

# Output file the compiler expects.
out="$(printf %q "$1")"
shift

# Create the file the compiler expects.  It will check syntax.
>"$out"

cpp='cpp'
opts=''
while test "$#" != 0; do
    case "$1" in
    # Extract the option for the path to cpp.
    --cpp) shift; cpp="$(printf %q "$1")" ;;
    # Extract the option for our own output file.
    --out) shift; out="$(printf %q "$1")" ;;
    # Collect the rest of the command line.
    *) opts="$opts $(printf %q "$1")" ;;
    esac
    shift
done

# Execute the real preprocessor tool.
eval "exec $cpp $src $out $opts"
