kompile.cli.version=${project.version}
project.version=${project.version}
kompile.app.version=${project.version}
spring.boot.version=${spring-boot.version}
spring.ai.version=${spring-ai.version}
native.image.plugin.version=${native-maven-plugin.version}
maven.compiler.plugin.version=${maven-compiler-plugin.version}
maven.resources.plugin.version=${maven-resources-plugin.version}
maven.assembly.plugin.version=3.7.1
frontend.maven.plugin.version=${frontend-maven-plugin.version}
os.maven.plugin.version=1.7.1
