package ai.kompile.pipelines.framework.api.context;

import lombok.Builder;
import lombok.Data; // Using Lombok's @Data for getters, setters, equals, hashCode, toString
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Represents a single event in a trace, typically generated by a {@link Profiler}.
 * This class is a simple data holder and might be used by Profiler implementations
 * to store or transmit trace data. It implements {@link Serializable} to allow
 * it to be part of configurations or passed across different systems if needed.
 */
@Data // Generates getters, setters, equals, hashCode, toString
@Builder
@NoArgsConstructor // For Jackson or other deserializers
@AllArgsConstructor
public class TraceEvent implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * The descriptive name of the event.
     */
    private String name;

    /**
     * The system time in nanoseconds when the event started
     * (e.g., from {@link System#nanoTime()}).
     */
    private long startTimeNanos;

    /**
     * The system time in nanoseconds when the event ended.
     */
    private long endTimeNanos;

    /**
     * The duration of the event in nanoseconds (endTimeNanos - startTimeNanos).
     */
    private long durationNanos;

    /**
     * The name of the thread where this event occurred.
     */
    private String threadName;

    /**
     * The ID of the thread where this event occurred.
     */
    private long threadId;

    // Optional fields for more detailed tracing:
    // private String category; // e.g., "IO", "CPU", "MODEL"
    // private Map<String, String> metadata; // Additional key-value metadata for the event
    // private String parentEventId; // For hierarchical traces
    // private int depth; // For hierarchical traces
}