/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.pipelines.framework.api.context;

import lombok.Builder;
import lombok.Data; // Using Lombok's @Data for getters, setters, equals, hashCode, toString
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Represents a single event in a trace, typically generated by a {@link Profiler}.
 * This class is a simple data holder and might be used by Profiler implementations
 * to store or transmit trace data. It implements {@link Serializable} to allow
 * it to be part of configurations or passed across different systems if needed.
 */
@Data // Generates getters, setters, equals, hashCode, toString
@Builder
@NoArgsConstructor // For Jackson or other deserializers
@AllArgsConstructor
public class TraceEvent implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * The descriptive name of the event.
     */
    private String name;

    /**
     * The system time in nanoseconds when the event started
     * (e.g., from {@link System#nanoTime()}).
     */
    private long startTimeNanos;

    /**
     * The system time in nanoseconds when the event ended.
     */
    private long endTimeNanos;

    /**
     * The duration of the event in nanoseconds (endTimeNanos - startTimeNanos).
     */
    private long durationNanos;

    /**
     * The name of the thread where this event occurred.
     */
    private String threadName;

    /**
     * The ID of the thread where this event occurred.
     */
    private long threadId;

    // Optional fields for more detailed tracing:
    // private String category; // e.g., "IO", "CPU", "MODEL"
    // private Map<String, String> metadata; // Additional key-value metadata for the event
    // private String parentEventId; // For hierarchical traces
    // private int depth; // For hierarchical traces
}