/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.core.rag;

import org.springframework.ai.chat.messages.Message;
import reactor.core.publisher.Flux;

import java.util.List;

/**
 * Conversational RAG (Retrieval-Augmented Generation) service with memory support.
 * <p>
 * This service orchestrates the full RAG pipeline with conversation context:
 * <ol>
 *   <li><b>Query Processing:</b> Transform conversational queries into standalone retrieval queries</li>
 *   <li><b>Retrieval:</b> Hybrid semantic + keyword search using optimized INDArray operations</li>
 *   <li><b>Context Building:</b> Format retrieved documents and history for the LLM</li>
 *   <li><b>Generation:</b> Generate responses using the LLM with full context</li>
 *   <li><b>Memory Management:</b> Update conversation history</li>
 * </ol>
 *
 * <h2>Performance Characteristics</h2>
 * <ul>
 *   <li>Uses INDArray-native vector operations (no float[] boxing)</li>
 *   <li>Single embedding generation per query</li>
 *   <li>Hybrid retrieval combining semantic and keyword search</li>
 *   <li>Integrates with Spring AI's ChatMemory for conversation persistence</li>
 * </ul>
 *
 * <h2>Usage Example</h2>
 * <pre>
 * // Simple conversation
 * ConversationalRagResult result = ragService.chat("conv-123", "What's in the report?");
 * System.out.println(result.answer());
 *
 * // Follow-up question (uses conversation context)
 * result = ragService.chat("conv-123", "Tell me more about the performance section");
 *
 * // Streaming response
 * ragService.chatStream("conv-123", "Summarize the findings")
 *     .subscribe(chunk -> System.out.print(chunk));
 * </pre>
 *
 * @see ConversationalRagOptions
 * @see ConversationalRagResult
 */
public interface ConversationalRagService {

    /**
     * Processes a conversational RAG query with default options.
     *
     * @param conversationId Unique identifier for the conversation
     * @param userMessage The user's message/query
     * @return Result containing the answer, retrieved documents, and metadata
     */
    ConversationalRagResult chat(String conversationId, String userMessage);

    /**
     * Processes a conversational RAG query with custom options.
     *
     * @param conversationId Unique identifier for the conversation
     * @param userMessage The user's message/query
     * @param options Configuration for retrieval and generation
     * @return Result containing the answer, retrieved documents, and metadata
     */
    ConversationalRagResult chat(String conversationId, String userMessage, ConversationalRagOptions options);

    /**
     * Processes a conversational RAG query with streaming response.
     * <p>
     * Emits response chunks as they are generated by the LLM.
     *
     * @param conversationId Unique identifier for the conversation
     * @param userMessage The user's message/query
     * @return Flux of response text chunks
     */
    Flux<String> chatStream(String conversationId, String userMessage);

    /**
     * Processes a conversational RAG query with streaming and custom options.
     *
     * @param conversationId Unique identifier for the conversation
     * @param userMessage The user's message/query
     * @param options Configuration for retrieval and generation
     * @return Flux of response text chunks
     */
    Flux<String> chatStream(String conversationId, String userMessage, ConversationalRagOptions options);

    // ═══════════════════════════════════════════════════════════════════════════
    // CONVERSATION MANAGEMENT
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Clears the conversation history for a specific conversation.
     *
     * @param conversationId The conversation to clear
     */
    void clearConversation(String conversationId);

    /**
     * Retrieves the conversation history.
     *
     * @param conversationId The conversation ID
     * @return List of messages in the conversation
     */
    List<Message> getConversationHistory(String conversationId);

    /**
     * Checks if a conversation exists and has messages.
     *
     * @param conversationId The conversation ID
     * @return true if conversation exists with messages
     */
    boolean hasConversation(String conversationId);

    /**
     * Gets the number of messages in a conversation.
     *
     * @param conversationId The conversation ID
     * @return Number of messages
     */
    default int getConversationSize(String conversationId) {
        List<Message> history = getConversationHistory(conversationId);
        return history != null ? history.size() : 0;
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // BACKWARD COMPATIBILITY
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Processes a stateless RAG query (no conversation context).
     * <p>
     * For backward compatibility with {@link RagService}.
     *
     * @param query The RAG query
     * @return RAG result
     */
    default RagResult answerQuery(RagQuery query) {
        ConversationalRagOptions options = ConversationalRagOptions.fromRagQuery(query);
        // Use a transient conversation ID for stateless queries
        String tempConversationId = "stateless-" + System.currentTimeMillis();
        try {
            ConversationalRagResult result = chat(tempConversationId, query.getQuery(), options);
            return result.toRagResult();
        } finally {
            // Clean up transient conversation
            clearConversation(tempConversationId);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // STATUS
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Checks if this service is ready to handle requests.
     *
     * @return true if all required components are available
     */
    default boolean isAvailable() {
        return true;
    }
}
