/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.cli.main.mcp;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Auto-configures tool call visibility hooks across all supported AI coding tools:
 * Claude Code, Codex CLI, OpenCode, and Gemini CLI.
 *
 * <p>Each platform uses a different config format but the goal is the same:
 * show tool name + params before execution, show tool name + timing after execution,
 * and log everything to {@code ~/.kompile/logs/mcp-activity.log}.</p>
 *
 * <p>All methods are idempotent — they check for existing kompile hooks before writing.</p>
 */
public class PlatformHooksInstaller {

    private static final String MARKER = "kompile";

    private final Path projectDir;
    private final PrintStream out;
    /** Per-project temp file for timing — avoids cross-project contamination. */
    private final String tsFile;

    public PlatformHooksInstaller(Path projectDir, PrintStream out) {
        this.projectDir = projectDir;
        this.out = out;
        String wdHash = Integer.toHexString(projectDir.toAbsolutePath().toString().hashCode() & 0x7fffffff);
        this.tsFile = "/tmp/.kompile_hook_ts_" + wdHash;
    }

    /**
     * Install hooks for all detected/supported platforms.
     * Non-fatal — failures for one platform don't affect others.
     */
    public void installAll() {
        installCodex();
        installOpenCode();
        installGemini();
    }

    // ── Codex CLI ────────────────────────────────────────────────────────────

    /**
     * Install hooks into {@code .codex/config.toml} (project-level).
     * Codex uses the same PreToolUse/PostToolUse events and mcp__kompile__ prefix as Claude Code.
     */
    public void installCodex() {
        try {
            Path codexDir = projectDir.resolve(".codex");
            Path configFile = codexDir.resolve("config.toml");

            // Check if already configured
            if (Files.exists(configFile)) {
                String existing = Files.readString(configFile, StandardCharsets.UTF_8);
                if (existing.contains("kompile")) {
                    out.println("[Hooks] Codex: already configured");
                    return;
                }
                // Append hooks to existing config
                Files.writeString(configFile, existing + "\n" + codexHooksToml(), StandardCharsets.UTF_8);
            } else {
                Files.createDirectories(codexDir);
                Files.writeString(configFile, codexHooksToml(), StandardCharsets.UTF_8);
            }
            out.println("[Hooks] Codex: configured .codex/config.toml");
        } catch (IOException e) {
            out.println("[Hooks] Codex: failed — " + e.getMessage());
        }
    }

    private String codexHooksToml() {
        // Codex uses TOML with [[hooks.PreToolUse]] arrays
        // MCP tool naming is identical to Claude Code: mcp__kompile__<tool>
        // Hooks are display-only (stderr logging) — no permissionDecision output.
        String preCmd = escapeToml("bash -c '"
                + "INPUT=$(cat); "
                + "TN=$(echo \"$INPUT\" | jq -r \".tool_name // \\\"unknown\\\"\"); "
                + "SHORT=${TN#mcp__kompile__}; "
                + "PARAMS=$(echo \"$INPUT\" | jq -rc \".tool_input // {}\" | head -c 120); "
                + "echo \"$(($(date +%s%N)/1000000))\" > " + tsFile + "; "
                + "echo >&2 \"[kompile] $SHORT | $PARAMS\""
                + "'");

        String postCmd = escapeToml("bash -c '"
                + "INPUT=$(cat); "
                + "TN=$(echo \"$INPUT\" | jq -r \".tool_name // \\\"unknown\\\"\"); "
                + "SHORT=${TN#mcp__kompile__}; "
                + "END=$(($(date +%s%N)/1000000)); "
                + "START=$(cat " + tsFile + " 2>/dev/null || echo $END); "
                + "MS=$((END - START)); "
                + "if [ $MS -gt 1000 ]; then FMT=\"$((MS/1000)).$((MS%1000/100))s\"; else FMT=\"${MS}ms\"; fi; "
                + "echo >&2 \"[kompile] $SHORT done ($FMT)\""
                + "'");

        return "# ── Kompile MCP tool visibility hooks ─────────────────────────────\n"
                + "# Auto-generated by kompile init. Shows tool name, params, and timing.\n\n"
                + "[[hooks.PreToolUse]]\n"
                + "matcher = \".*\"\n\n"
                + "[[hooks.PreToolUse.hooks]]\n"
                + "type = \"command\"\n"
                + "command = \"" + preCmd + "\"\n"
                + "statusMessage = \"Running kompile tool...\"\n\n"
                + "[[hooks.PostToolUse]]\n"
                + "matcher = \".*\"\n\n"
                + "[[hooks.PostToolUse.hooks]]\n"
                + "type = \"command\"\n"
                + "command = \"" + postCmd + "\"\n";
    }

    /** Escape a string for use inside a TOML basic (double-quoted) string. */
    private static String escapeToml(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }

    // ── OpenCode ─────────────────────────────────────────────────────────────

    /**
     * Install a TypeScript plugin at {@code .opencode/plugins/kompile-hooks.ts}.
     * OpenCode uses plugin files with tool.execute.before/after hooks.
     */
    public void installOpenCode() {
        try {
            Path pluginDir = projectDir.resolve(".opencode").resolve("plugins");
            Path pluginFile = pluginDir.resolve("kompile-hooks.ts");

            if (Files.exists(pluginFile)) {
                out.println("[Hooks] OpenCode: already configured");
                return;
            }

            Files.createDirectories(pluginDir);
            Files.writeString(pluginFile, openCodePlugin(), StandardCharsets.UTF_8);
            out.println("[Hooks] OpenCode: configured .opencode/plugins/kompile-hooks.ts");
        } catch (IOException e) {
            out.println("[Hooks] OpenCode: failed — " + e.getMessage());
        }
    }

    private String openCodePlugin() {
        return """
                /**
                 * Kompile MCP tool visibility plugin for OpenCode.
                 * Auto-generated by kompile init.
                 *
                 * Shows tool name + params before execution, timing after.
                 * Logs to ~/.kompile/logs/mcp-activity.log via the kompile MCP server.
                 */
                import type { Plugin } from "@opencode-ai/plugin"

                const startTimes = new Map<string, number>()

                export const server: Plugin = async ({ $ }) => {
                  return {
                    "tool.execute.before": async (input, output) => {
                      const short = input.tool.replace(/^mcp_+kompile_+/, "")
                      const params = JSON.stringify(output.args).slice(0, 120)
                      startTimes.set(input.callID, Date.now())
                      console.error(`[kompile] ${short} | ${params}`)
                    },

                    "tool.execute.after": async (input, output) => {
                      const short = input.tool.replace(/^mcp_+kompile_+/, "")
                      const start = startTimes.get(input.callID) ?? Date.now()
                      startTimes.delete(input.callID)
                      const ms = Date.now() - start
                      const fmt = ms > 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms}ms`
                      console.error(`[kompile] ${short} done (${fmt})`)
                      // Inject timing into model context
                      output.metadata = { ...output.metadata, kompile_elapsed: fmt }
                    },
                  }
                }
                """;
    }

    // ── Gemini CLI ───────────────────────────────────────────────────────────

    /**
     * Install hooks into {@code .gemini/settings.json} (project-level).
     * Gemini uses BeforeTool/AfterTool events and mcp_kompile_ prefix (single underscore).
     * Uses Jackson for proper JSON merge instead of string-splice.
     */
    public void installGemini() {
        try {
            Path geminiDir = projectDir.resolve(".gemini");
            Path settingsFile = geminiDir.resolve("settings.json");

            var mapper = new com.fasterxml.jackson.databind.ObjectMapper();
            com.fasterxml.jackson.databind.node.ObjectNode settings;

            if (Files.exists(settingsFile)) {
                String existing = Files.readString(settingsFile, StandardCharsets.UTF_8);
                if (existing.contains("kompile")) {
                    out.println("[Hooks] Gemini: already configured");
                    return;
                }
                var parsed = mapper.readTree(existing);
                settings = parsed.isObject()
                        ? (com.fasterxml.jackson.databind.node.ObjectNode) parsed
                        : mapper.createObjectNode();
            } else {
                Files.createDirectories(geminiDir);
                settings = mapper.createObjectNode();
            }

            // Build hooks structure programmatically
            var hooks = settings.has("hooks") && settings.get("hooks").isObject()
                    ? (com.fasterxml.jackson.databind.node.ObjectNode) settings.get("hooks")
                    : settings.putObject("hooks");

            // BeforeTool
            var beforeArray = hooks.putArray("BeforeTool");
            var beforeEntry = beforeArray.addObject();
            beforeEntry.put("matcher", ".*");
            var beforeHookArr = beforeEntry.putArray("hooks");
            var beforeHook = beforeHookArr.addObject();
            beforeHook.put("name", "kompile-progress");
            beforeHook.put("type", "command");
            beforeHook.put("command", geminiPreCmd());

            // AfterTool
            var afterArray = hooks.putArray("AfterTool");
            var afterEntry = afterArray.addObject();
            afterEntry.put("matcher", ".*");
            var afterHookArr = afterEntry.putArray("hooks");
            var afterHook = afterHookArr.addObject();
            afterHook.put("name", "kompile-timing");
            afterHook.put("type", "command");
            afterHook.put("command", geminiPostCmd());

            Files.writeString(settingsFile,
                    mapper.writerWithDefaultPrettyPrinter().writeValueAsString(settings),
                    StandardCharsets.UTF_8);
            out.println("[Hooks] Gemini: configured .gemini/settings.json");
        } catch (IOException e) {
            out.println("[Hooks] Gemini: failed — " + e.getMessage());
        }
    }

    /** Gemini BeforeTool hook command — stderr-only display, no permission override. */
    private String geminiPreCmd() {
        return "bash -c 'INPUT=$(cat); TN=$(echo \"$INPUT\" | jq -r \".tool_name // \\\"unknown\\\"\"); "
                + "SHORT=${TN#mcp_kompile_}; "
                + "PARAMS=$(echo \"$INPUT\" | jq -rc \".tool_input // {}\" | head -c 120); "
                + "echo \"$(($(date +%s%N)/1000000))\" > " + tsFile + "; "
                + "echo >&2 \"[kompile] $SHORT | $PARAMS\"'";
    }

    /** Gemini AfterTool hook command — stderr-only timing display. */
    private String geminiPostCmd() {
        return "bash -c 'INPUT=$(cat); TN=$(echo \"$INPUT\" | jq -r \".tool_name // \\\"unknown\\\"\"); "
                + "SHORT=${TN#mcp_kompile_}; "
                + "END=$(($(date +%s%N)/1000000)); "
                + "START=$(cat " + tsFile + " 2>/dev/null || echo $END); "
                + "MS=$((END - START)); "
                + "if [ $MS -gt 1000 ]; then FMT=\"$((MS/1000)).$((MS%1000/100))s\"; else FMT=\"${MS}ms\"; fi; "
                + "echo >&2 \"[kompile] $SHORT done ($FMT)\"'";
    }
}
