#!/usr/bin/env bash
#
# Launcher for kompile-fpna-v6
# Generated by kompile build app
#
# Usage:
#   bin/run.sh
#   bin/run.sh --server.port=9090
#

set -e

SOURCE="${BASH_SOURCE[0]}"
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
APP_HOME="$(cd "${SCRIPT_DIR}/.." && pwd)"

NATIVE_BIN="${APP_HOME}/bin/kompile-fpna-v6-native"

# Library paths for GraalVM shared libs and ND4J/bytedeco native libraries
export LD_LIBRARY_PATH="${APP_HOME}/bin${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export DYLD_LIBRARY_PATH="${APP_HOME}/bin${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
# Add all directories under lib/ containing platform native libraries
if [ -d "${APP_HOME}/lib" ]; then
    while IFS= read -r d; do
        LD_LIBRARY_PATH="${d}:${LD_LIBRARY_PATH}"
        DYLD_LIBRARY_PATH="${d}:${DYLD_LIBRARY_PATH}"
    done < <(find "${APP_HOME}/lib" -type f \( -name '*.so' -o -name '*.so.*' -o -name '*.dylib' -o -name '*.dll' \) -exec dirname {} \; | sort -u)
    export LD_LIBRARY_PATH DYLD_LIBRARY_PATH
fi

if [ ! -x "${NATIVE_BIN}" ]; then
    echo "error: native binary not found: ${NATIVE_BIN}" >&2
    exit 1
fi

echo "[kompile-fpna-v6] Starting native binary"
exec "${NATIVE_BIN}" \
    -Dspring.config.additional-location="optional:file:${APP_HOME}/conf/" \
    "$@"
