import Foundation

/// Simple in-memory vector similarity search service.
/// Stores document chunks with their embedding vectors and supports
/// cosine similarity search for retrieval-augmented generation.
final class VectorSearchService: ObservableObject {
    @Published var indexedChunkCount: Int = 0
    @Published var isIndexing: Bool = false

    struct IndexedChunk: Identifiable {
        let id: UUID
        let text: String
        let embedding: [Float]
    }

    private var chunks: [IndexedChunk] = []
    private let indexQueue = DispatchQueue(label: "{{packageName}}.vector.index", qos: .userInitiated)

    /// Indexes an array of text chunks by generating placeholder embeddings.
    /// In production, embeddings should be generated by the SdxInferenceService.
    /// - Parameter chunks: Array of text strings to index.
    func index(chunks: [String]) async {
        await MainActor.run { isIndexing = true }

        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            indexQueue.async { [weak self] in
                guard let self = self else {
                    continuation.resume()
                    return
                }

                let indexed = chunks.map { text in
                    IndexedChunk(
                        id: UUID(),
                        text: text,
                        embedding: self.generatePlaceholderEmbedding(for: text)
                    )
                }

                DispatchQueue.main.async {
                    self.chunks.append(contentsOf: indexed)
                    self.indexedChunkCount = self.chunks.count
                    self.isIndexing = false
                    continuation.resume()
                }
            }
        }
    }

    /// Indexes chunks with pre-computed embeddings.
    /// - Parameters:
    ///   - chunks: Array of text strings.
    ///   - embeddings: Corresponding embedding vectors for each chunk.
    func indexWithEmbeddings(chunks: [String], embeddings: [[Float]]) async {
        guard chunks.count == embeddings.count else { return }

        await MainActor.run { isIndexing = true }

        let indexed = zip(chunks, embeddings).map { text, embedding in
            IndexedChunk(id: UUID(), text: text, embedding: embedding)
        }

        await MainActor.run {
            self.chunks.append(contentsOf: indexed)
            self.indexedChunkCount = self.chunks.count
            self.isIndexing = false
        }
    }

    /// Searches for the most similar chunks to the query text.
    /// Uses a simple hash-based similarity for the placeholder implementation.
    /// - Parameters:
    ///   - query: The query text to search for.
    ///   - topK: The number of top results to return.
    /// - Returns: Array of the most relevant text chunks.
    func search(query: String, topK: Int) async -> [String] {
        let queryEmbedding = generatePlaceholderEmbedding(for: query)
        return await search(queryEmbedding: queryEmbedding, topK: topK)
    }

    /// Searches for the most similar chunks using a pre-computed query embedding.
    /// - Parameters:
    ///   - queryEmbedding: The embedding vector for the query.
    ///   - topK: The number of top results to return.
    /// - Returns: Array of the most relevant text chunks.
    func search(queryEmbedding: [Float], topK: Int) async -> [String] {
        guard !chunks.isEmpty else { return [] }

        let scored = chunks.map { chunk in
            (chunk.text, cosineSimilarity(queryEmbedding, chunk.embedding))
        }

        let sorted = scored.sorted { $0.1 > $1.1 }
        let results = sorted.prefix(topK).map { $0.0 }
        return Array(results)
    }

    /// Returns the total number of indexed chunks.
    var count: Int {
        return chunks.count
    }

    /// Removes all indexed chunks.
    func clear() {
        chunks.removeAll()
        indexedChunkCount = 0
    }

    // MARK: - Private

    /// Computes cosine similarity between two vectors.
    private func cosineSimilarity(_ a: [Float], _ b: [Float]) -> Float {
        guard a.count == b.count, !a.isEmpty else { return 0.0 }

        var dotProduct: Float = 0.0
        var normA: Float = 0.0
        var normB: Float = 0.0

        for i in 0..<a.count {
            dotProduct += a[i] * b[i]
            normA += a[i] * a[i]
            normB += b[i] * b[i]
        }

        let denominator = sqrt(normA) * sqrt(normB)
        guard denominator > 0 else { return 0.0 }

        return dotProduct / denominator
    }

    /// Generates a deterministic placeholder embedding based on text content.
    /// This is used when the native SameDiff library is not available.
    private func generatePlaceholderEmbedding(for text: String, dimensions: Int = 384) -> [Float] {
        var embedding = [Float](repeating: 0.0, count: dimensions)
        let words = text.lowercased().split(separator: " ")

        for (wordIndex, word) in words.enumerated() {
            var hash = word.hashValue
            for dim in 0..<dimensions {
                hash = hash &* 6364136223846793005 &+ 1442695040888963407
                let value = Float(hash & 0xFFFF) / Float(0xFFFF) * 2.0 - 1.0
                embedding[dim] += value / Float(max(words.count, 1))
            }
        }

        // Normalize
        let norm = sqrt(embedding.reduce(0) { $0 + $1 * $1 })
        if norm > 0 {
            embedding = embedding.map { $0 / norm }
        }

        return embedding
    }
}
