cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED MODE OR NOT DEFINED STAGE)
  message(FATAL_ERROR "MODE and STAGE are required")
endif()
cmake_path(ABSOLUTE_PATH STAGE NORMALIZE)
function(json_quote input output)
  set(v "${input}")
  string(REPLACE "\\" "\\\\" v "${v}")
  string(REPLACE "\"" "\\\"" v "${v}")
  string(REPLACE "\n" "\\n" v "${v}")
  string(REPLACE "\r" "\\r" v "${v}")
  string(REPLACE "\t" "\\t" v "${v}")
  set(${output} "\"${v}\"" PARENT_SCOPE)
endfunction()
function(role_for path output)
  if(path MATCHES "^artifacts/android/.*\\.sha256$")
    set(role apk-checksum)
  elseif(path MATCHES "^artifacts/android/")
    set(role android-apk)
  elseif(path MATCHES "^artifacts/runtime/")
    set(role accelerator-runtime)
  elseif(path MATCHES "^artifacts/graph/android-")
    set(role android-graph-aot)
  elseif(path MATCHES "^artifacts/graph/")
    set(role graph-aot)
  elseif(path MATCHES "^artifacts/models/")
    set(role canonical-sdz-fixture)
  elseif(path MATCHES "^artifacts/contracts/")
    set(role accelerator-contract)
  elseif(path MATCHES "models|MODEL|research|catalog")
    set(role model-research-catalog)
  elseif(path MATCHES "^source/")
    set(role application-source)
  elseif(path STREQUAL "README.md")
    set(role bundle-readme)
  else()
    set(role bundle-content)
  endif()
  set(${output} "${role}" PARENT_SCOPE)
endfunction()
if(MODE STREQUAL "manifest")
  file(GLOB_RECURSE files RELATIVE "${STAGE}" LIST_DIRECTORIES false "${STAGE}/*")
  list(REMOVE_ITEM files "MANIFEST.json")
  list(SORT files)
  set(records "")
  foreach(path IN LISTS files)
    file(SIZE "${STAGE}/${path}" size)
    file(SHA256 "${STAGE}/${path}" sha)
    role_for("${path}" role)
    json_quote("${path}" qpath)
    json_quote("${role}" qrole)
    string(APPEND records "    {\"path\": ${qpath}, \"role\": ${qrole}, \"size\": ${size}, \"sha256\": \"${sha}\"},\n")
  endforeach()
  string(REGEX REPLACE ",\n$" "\n" records "${records}")
  if(DEFINED ENV{SOURCE_DATE_EPOCH} AND NOT "$ENV{SOURCE_DATE_EPOCH}" STREQUAL "")
    set(epoch "$ENV{SOURCE_DATE_EPOCH}")
    if(NOT epoch MATCHES "^[0-9]+$")
      message(FATAL_ERROR "SOURCE_DATE_EPOCH must be a non-negative integer")
    endif()
  else()
    set(epoch 0)
  endif()
  set(manifest "{\n  \"schemaVersion\": 1,\n  \"name\": \"kompile-offline-graph-chat\",\n  \"sourceDateEpoch\": ${epoch},\n  \"archiveTimestamp\": \"1980-01-01T00:00:00Z\",\n  \"networkPermission\": false,\n  \"modelsIncluded\": false,\n  \"canonicalSdzFixtureIncluded\": true,\n  \"canonicalSdzFixture\": \"artifacts/models/canonical-mlp.sdz\",\n  \"androidGraphRuntime\": \"stock-GraalVM-native-AOT-C-ABI-v1-via-JavaCPP\",\n  \"desktopGraphRuntime\": \"GraalVM-native-AOT-C-ABI-v1\",\n  \"androidNativeGraphAot\": {\"available\": true, \"abi\": \"arm64-v8a\", \"target\": \"aarch64-linux-android\", \"minimumSdk\": 28, \"kgrAbiVersion\": 1, \"transport\": \"JavaCPP\", \"crossCompiler\": \"Android NDK r28b clang/lld\", \"gluon\": false, \"openBlas\": false, \"libraries\": [\"libjnikompile_graph.so\", \"libkompile_reasoning_android.so\"]},\n  \"accelerators\": {\n    \"vulkan\": {\"abi\":\"arm64-v8a\",\"deviceOnly\":true,\"cpuFallback\":false,\"nnapiFallback\":false,\"openBlas\":false,\"gpuTarget\":\"VULKAN\",\"replay\":\"lowered-command-buffer\"},\n    \"hexagon\": {\"abi\":\"arm64-v8a\",\"deviceOnly\":true,\"cpuFallback\":false,\"openBlas\":false},\n    \"tensorG3\": {\"abi\":\"arm64-v8a\",\"deviceOnly\":true,\"cpuFallback\":false,\"openBlas\":false,\"quantization\":\"explicit INT8 metadata contract\",\"driverCompilation\":\"content-addressed NNAPI cache\"},\n    \"tensorG5\": {\"abi\":\"arm64-v8a\",\"deviceOnly\":true,\"cpuFallback\":false,\"openBlas\":false,\"quantization\":\"INT8 contract\"}\n  },\n  \"verificationScope\": \"signature, ABI, permission, provider, dependency, integrity and forbidden-library checks; physical-device execution not performed\",\n  \"files\": [\n${records}  ]\n}\n")
  file(WRITE "${STAGE}/MANIFEST.json" "${manifest}")
elseif(MODE STREQUAL "verify")
  if(NOT EXISTS "${STAGE}/MANIFEST.json")
    message(FATAL_ERROR "MANIFEST.json is missing")
  endif()
  file(READ "${STAGE}/MANIFEST.json" manifest)
  function(manifest_expect expected)
    string(JSON actual ERROR_VARIABLE err GET "${manifest}" ${ARGN})
    if(err OR NOT "${actual}" STREQUAL "${expected}")
      message(FATAL_ERROR
        "manifest policy mismatch at ${ARGN}: expected '${expected}', got '${actual}'")
    endif()
  endfunction()

  foreach(field schemaVersion name sourceDateEpoch archiveTimestamp networkPermission modelsIncluded canonicalSdzFixtureIncluded canonicalSdzFixture androidGraphRuntime desktopGraphRuntime androidNativeGraphAot accelerators verificationScope files)
    string(JSON type ERROR_VARIABLE err TYPE "${manifest}" "${field}")
    if(err)
      message(FATAL_ERROR "manifest field missing or invalid: ${field}: ${err}")
    endif()
  endforeach()

  string(JSON epoch_type TYPE "${manifest}" sourceDateEpoch)
  string(JSON epoch GET "${manifest}" sourceDateEpoch)
  if(NOT epoch_type STREQUAL "NUMBER" OR NOT epoch MATCHES "^[0-9]+$")
    message(FATAL_ERROR "manifest sourceDateEpoch must be a non-negative integer")
  endif()
  manifest_expect("1" schemaVersion)
  manifest_expect("kompile-offline-graph-chat" name)
  manifest_expect("1980-01-01T00:00:00Z" archiveTimestamp)
  manifest_expect("OFF" networkPermission)
  manifest_expect("OFF" modelsIncluded)
  manifest_expect("ON" canonicalSdzFixtureIncluded)
  manifest_expect("artifacts/models/canonical-mlp.sdz" canonicalSdzFixture)
  manifest_expect("stock-GraalVM-native-AOT-C-ABI-v1-via-JavaCPP" androidGraphRuntime)
  manifest_expect("GraalVM-native-AOT-C-ABI-v1" desktopGraphRuntime)
  manifest_expect("signature, ABI, permission, provider, dependency, integrity and forbidden-library checks; physical-device execution not performed" verificationScope)

  manifest_expect("ON" androidNativeGraphAot available)
  manifest_expect("arm64-v8a" androidNativeGraphAot abi)
  manifest_expect("aarch64-linux-android" androidNativeGraphAot target)
  manifest_expect("28" androidNativeGraphAot minimumSdk)
  manifest_expect("1" androidNativeGraphAot kgrAbiVersion)
  manifest_expect("JavaCPP" androidNativeGraphAot transport)
  manifest_expect("Android NDK r28b clang/lld" androidNativeGraphAot crossCompiler)
  manifest_expect("OFF" androidNativeGraphAot gluon)
  manifest_expect("OFF" androidNativeGraphAot openBlas)
  string(JSON graph_library_count LENGTH "${manifest}" androidNativeGraphAot libraries)
  if(NOT graph_library_count EQUAL 2)
    message(FATAL_ERROR "manifest graph library set must contain exactly two entries")
  endif()
  manifest_expect("libjnikompile_graph.so" androidNativeGraphAot libraries 0)
  manifest_expect("libkompile_reasoning_android.so" androidNativeGraphAot libraries 1)

  foreach(accelerator IN ITEMS vulkan hexagon tensorG3 tensorG5)
    manifest_expect("arm64-v8a" accelerators ${accelerator} abi)
    manifest_expect("ON" accelerators ${accelerator} deviceOnly)
    manifest_expect("OFF" accelerators ${accelerator} cpuFallback)
    manifest_expect("OFF" accelerators ${accelerator} openBlas)
  endforeach()
  manifest_expect("OFF" accelerators vulkan nnapiFallback)
  manifest_expect("VULKAN" accelerators vulkan gpuTarget)
  manifest_expect("lowered-command-buffer" accelerators vulkan replay)
  manifest_expect("explicit INT8 metadata contract" accelerators tensorG3 quantization)
  manifest_expect("content-addressed NNAPI cache" accelerators tensorG3 driverCompilation)
  manifest_expect("INT8 contract" accelerators tensorG5 quantization)

  string(JSON count LENGTH "${manifest}" files)
  set(listed "")
  if(count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(i RANGE 0 ${last})
      foreach(field path role size sha256)
        string(JSON value ERROR_VARIABLE err GET "${manifest}" files ${i} ${field})
        if(err)
          message(FATAL_ERROR "manifest file record ${i} field ${field} is invalid")
        endif()
        set(${field} "${value}")
      endforeach()
      if(path MATCHES "^/" OR path MATCHES "(^|/)\\.\\.(/|$)" OR path MATCHES "\\\\")
        message(FATAL_ERROR "unsafe manifest path: ${path}")
      endif()
      list(FIND listed "${path}" duplicate)
      if(NOT duplicate EQUAL -1)
        message(FATAL_ERROR "duplicate manifest path: ${path}")
      endif()
      list(APPEND listed "${path}")
      if(NOT EXISTS "${STAGE}/${path}" OR IS_DIRECTORY "${STAGE}/${path}")
        message(FATAL_ERROR "manifest member missing: ${path}")
      endif()
      file(SIZE "${STAGE}/${path}" actual_size)
      file(SHA256 "${STAGE}/${path}" actual_sha)
      if(NOT actual_size EQUAL size OR NOT actual_sha STREQUAL sha256)
        message(FATAL_ERROR "manifest integrity mismatch: ${path}")
      endif()
    endforeach()
  endif()
  file(GLOB_RECURSE actual RELATIVE "${STAGE}" LIST_DIRECTORIES false "${STAGE}/*")
  list(REMOVE_ITEM actual "MANIFEST.json")
  list(SORT actual)
  list(SORT listed)
  if(NOT actual STREQUAL listed)
    message(FATAL_ERROR "bundle contains unmanifested or missing members")
  endif()
else()
  message(FATAL_ERROR "unknown MODE: ${MODE}")
endif()
