cmake_minimum_required(VERSION 3.20)

if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "Kompile mobile packaging requires a Linux/GNU build host")
endif()

foreach(required IN ITEMS VARIANT ANDROID_SDK ANDROID_NDK JAVA_HOME_DIR MAVEN_EXECUTABLE MAVEN_OFFLINE DL4J_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing mobile Maven property: ${required}")
  endif()
  string(FIND "${${required}}" "\n" newline_index)
  string(FIND "${${required}}" "\r" carriage_return_index)
  if(NOT newline_index EQUAL -1 OR NOT carriage_return_index EQUAL -1)
    message(FATAL_ERROR "Unsafe newline in mobile Maven property: ${required}")
  endif()
endforeach()

if(NOT MAVEN_OFFLINE STREQUAL "true")
  message(FATAL_ERROR "The outer Maven build must run offline; add -o")
endif()

set(supported_variants all vulkan hexagon tensor-g3 tensor-g5)
list(FIND supported_variants "${VARIANT}" variant_index)
if(variant_index EQUAL -1)
  message(FATAL_ERROR
    "Unsupported kompile.mobile='${VARIANT}'; expected all, vulkan, hexagon, tensor-g3, or tensor-g5")
endif()

if(NOT IS_DIRECTORY "${ANDROID_SDK}")
  message(FATAL_ERROR "Android SDK directory not found: ${ANDROID_SDK}")
endif()
if(NOT EXISTS "${ANDROID_NDK}/build/cmake/android.toolchain.cmake")
  message(FATAL_ERROR "Android NDK toolchain not found: ${ANDROID_NDK}")
endif()
if(NOT EXISTS "${ANDROID_NDK}/source.properties")
  message(FATAL_ERROR "Android NDK source.properties not found: ${ANDROID_NDK}")
endif()
file(READ "${ANDROID_NDK}/source.properties" ndk_properties)
if(NOT ndk_properties MATCHES "Pkg\\.Revision[ \\t]*=[ \\t]*28\\.1\\.13356709")
  message(FATAL_ERROR "Android NDK r28b (28.1.13356709) is required")
endif()
if(NOT EXISTS "${JAVA_HOME_DIR}/bin/java")
  message(FATAL_ERROR "JDK executable not found below mobile.java.home: ${JAVA_HOME_DIR}")
endif()
if(NOT EXISTS "${MAVEN_EXECUTABLE}")
  message(FATAL_ERROR "Maven executable not found: ${MAVEN_EXECUTABLE}")
endif()
if(NOT IS_DIRECTORY "${DL4J_ROOT}/libnd4j/tools/mobile")
  message(FATAL_ERROR "deeplearning4j mobile build root not found: ${DL4J_ROOT}")
endif()

message(STATUS
  "Kompile mobile Maven profile: variant=${VARIANT}, NDK=28.1.13356709, lifecycle=profile-gated")
