/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.app.facts.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * A user-authored or AI-generated note attached to a FactSheet.
 *
 * FactSheet IS Kompile's notebook primitive — Notes layer on top of it. They are
 * embedded into the same vector store as Facts so that hybrid search crosses both
 * sources and notes uniformly. The embedding is stored as a comma-separated float
 * string (or left null until NoteEmbeddingService processes the note asynchronously).
 *
 * Citation: a note may reference the source it was derived from (sourceOriginRef)
 * using the same SourceMetadataConstants.SOURCE_ID pattern as the rest of the
 * retrieval pipeline.
 */
@Entity
@Table(name = "notebook_notes", indexes = {
    @Index(name = "idx_note_fact_sheet", columnList = "factSheetId"),
    @Index(name = "idx_note_type", columnList = "noteType"),
    @Index(name = "idx_note_created", columnList = "createdAt"),
    @Index(name = "idx_note_embedded", columnList = "embedded")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Note {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /** The FactSheet this note belongs to. */
    @Column(nullable = false)
    private Long factSheetId;

    /** Optional short title / heading for the note. */
    @Column(length = 512)
    private String title;

    /** Full text content of the note. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /** Who or what created this note. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private NoteType noteType = NoteType.HUMAN;

    /**
     * Optional back-reference to the source (Fact) or chat response that this note
     * was derived from.  Stores the SourceMetadataConstants.SOURCE_ID value of the
     * originating chunk so the UI can resolve a citation link.
     */
    @Column(length = 1024)
    private String sourceOriginRef;

    /**
     * Comma-separated float values representing the embedding vector for this note.
     * Null until NoteEmbeddingService has processed the note.
     * Stored as TEXT for portability; the note embedding service converts it to/from float[].
     */
    @Column(columnDefinition = "TEXT")
    private String embeddingData;

    /** Whether this note has been embedded into the vector store. */
    @Column(nullable = false)
    @Builder.Default
    private Boolean embedded = false;

    /** Comma-separated tags for categorization. */
    @Column(length = 1024)
    private String tags;

    @Column(nullable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private Instant updatedAt;

    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        if (updatedAt == null) updatedAt = now;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }

    /** Mark the note as embedded. */
    public void markEmbedded() {
        this.embedded = true;
        this.updatedAt = Instant.now();
    }

    /** Whether this note needs embedding. */
    public boolean needsEmbedding() {
        return !Boolean.TRUE.equals(this.embedded);
    }

    /** Type of note author. */
    public enum NoteType {
        /** Written by a human user. */
        HUMAN,
        /** Generated by an AI agent or LLM. */
        AI
    }
}
