#!/usr/bin/env bash
#
# 03-start-app.sh
#
# Boot the generated demo RAG app on port 8080 connected to the demo staging
# server (8090). This launches the Spring Boot fat jar generated by
# `kompile build app` under generated/demo/project/target, NOT kompile-app-main
# directly — that module is an nd4j-backend-agnostic library.

set -euo pipefail

DEMO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${DEMO_DIR}/.." && pwd)"
APP_PROJECT="${DEMO_DIR}/generated/demo/project"
APP_TARGET="${APP_PROJECT}/target"
LOG_DIR="${DEMO_DIR}/logs"
PID_DIR="${DEMO_DIR}/.pids"
PID_FILE="${PID_DIR}/app.pid"
LOG_FILE="${LOG_DIR}/app.log"
HEALTH_URL="http://localhost:8080/actuator/health"
APP_CONFIG="${DEMO_DIR}/conf/app.properties"

# Demo-local kompile install dir. Keeps AppIndexConfigService state and all
# derived fact-sheet / anserini index paths isolated to this demo instead of
# polluting the user-global ~/.kompile. Passed to the JVM as -Dkompile.data.dir.
DEMO_DATA_DIR="${DEMO_DIR}/var"
CLI_JAR="${REPO_ROOT}/kompile-cli/target/kompile-cli-0.1.0-SNAPSHOT-shaded.jar"

mkdir -p "${LOG_DIR}" "${PID_DIR}"

log() { printf '[03-start-app] %s\n' "$*"; }

if curl -fsS "${HEALTH_URL}" >/dev/null 2>&1; then
    log "demo app already healthy at ${HEALTH_URL}"
    exit 0
fi

# Locate the generated fat jar (Spring Boot repackaged). Prefer the primary
# artifact over the *.jar.original (pre-repackage library jar).
APP_JAR=""
if [[ -d "${APP_TARGET}" ]]; then
    APP_JAR="$(find "${APP_TARGET}" -maxdepth 1 -type f -name 'demo-*.jar' \
        ! -name '*.jar.original' ! -name '*-sources.jar' ! -name '*-javadoc.jar' \
        | sort | tail -n1)"
fi

if [[ -z "${APP_JAR}" || ! -f "${APP_JAR}" ]]; then
    log "ERROR: no demo-*.jar found under ${APP_TARGET}"
    log "       Build it first: (cd ${APP_PROJECT} && mvn -o -DskipTests package)"
    exit 1
fi

log "starting demo app from: ${APP_JAR}"
log "logs: ${LOG_FILE}"
log "config overlay: ${APP_CONFIG}"
log "install dir: ${DEMO_DATA_DIR}"

JAVA_BIN="${JAVA_HOME:+${JAVA_HOME}/bin/}java"

if [[ -f "${CLI_JAR}" ]]; then
    "${JAVA_BIN}" -jar "${CLI_JAR}" init --installDir="${DEMO_DATA_DIR}" >/dev/null
else
    log "WARN: kompile CLI shaded jar not found at ${CLI_JAR}; creating install dir layout directly"
    mkdir -p "${DEMO_DATA_DIR}/config" "${DEMO_DATA_DIR}/fact-sheets" "${DEMO_DATA_DIR}/archives" "${DEMO_DATA_DIR}/anserini/indexes"
fi

nohup "${JAVA_BIN}" \
    -Xmx6g \
    -Dkompile.data.dir="${DEMO_DATA_DIR}" \
    -Dspring.config.additional-location="file:${APP_CONFIG}" \
    -jar "${APP_JAR}" \
    --kompile.staging.url=http://localhost:8090 \
    >> "${LOG_FILE}" 2>&1 &
echo $! > "${PID_FILE}"
log "started PID $(cat "${PID_FILE}")"

log "waiting for ${HEALTH_URL} ..."
deadline=$(( SECONDS + 600 ))   # 10 minutes — first run does heavy ND4J init
until curl -fsS "${HEALTH_URL}" 2>/dev/null | grep -q '"status":"UP"'; do
    if (( SECONDS > deadline )); then
        log "ERROR: kompile-app-main did not become healthy in 600s"
        log "       tail -n 80 ${LOG_FILE}"
        tail -n 80 "${LOG_FILE}" || true
        exit 1
    fi
    if ! kill -0 "$(cat "${PID_FILE}")" 2>/dev/null; then
        log "ERROR: parent PID exited (mvn wrapper)"
        tail -n 80 "${LOG_FILE}" || true
        exit 1
    fi
    sleep 3
done

log "kompile-app-main is healthy at ${HEALTH_URL}"
