/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.app.diagnostics.service;

import ai.kompile.app.diagnostics.dto.AllocationEntry;
import ai.kompile.app.diagnostics.dto.AllocationLogSummary;
import ai.kompile.app.diagnostics.dto.AllocationRateStats;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Parser for ADR 53 allocation log files.
 *
 * Parses logs generated by the AllocationLogger (NDArray and OpContext allocations).
 *
 * IMPORTANT: Allocation logging is AUTOMATIC in functrace builds (SD_GCC_FUNCTRACE).
 * When libnd4j is built with -Dlibnd4j.calltrace=ON, all allocations are automatically
 * logged to /tmp/nd4j_allocations_<PID>.log - no runtime configuration needed.
 *
 * This parser provides read-only analysis of those automatically-generated log files.
 */
@Slf4j
@Service
public class AllocationLogParser {

    private static final Pattern NDARRAY_ALLOCATION_PATTERN =
        Pattern.compile("NDARRAY ALLOCATION #(\\d+)");
    private static final Pattern OPCONTEXT_ALLOCATION_PATTERN =
        Pattern.compile("OPCONTEXT ALLOCATION #(\\d+)");
    private static final Pattern PTR_PATTERN = Pattern.compile("PTR: (0x[0-9a-fA-F]+)");
    private static final Pattern SIZE_PATTERN = Pattern.compile("SIZE: (\\d+) bytes");
    private static final Pattern DTYPE_PATTERN = Pattern.compile("DTYPE: (\\w+)");
    private static final Pattern SHAPE_PATTERN = Pattern.compile("SHAPE: \\[([^\\]]+)\\]");
    private static final Pattern IS_VIEW_PATTERN = Pattern.compile("IS_VIEW: (true|false)");
    private static final Pattern OPERATION_PATTERN = Pattern.compile("OPERATION: (.+)");
    private static final Pattern NUM_INPUTS_PATTERN = Pattern.compile("NUM_INPUTS: (\\d+)");
    private static final Pattern NUM_OUTPUTS_PATTERN = Pattern.compile("NUM_OUTPUTS: (\\d+)");
    private static final Pattern TIMESTAMP_PATTERN = Pattern.compile("TIMESTAMP: (\\d+)");
    private static final Pattern THREAD_PATTERN = Pattern.compile("THREAD: (0x[0-9a-fA-F]+)");
    private static final Pattern STACK_FRAME_PATTERN = Pattern.compile("^\\s*#\\d+\\s+(.+)$");

    /**
     * Parse allocation log file and return summary.
     */
    public AllocationLogSummary parseAllocationLog(String logFilePath) {
        return parseAllocationLog(logFilePath, 20, 10);
    }

    /**
     * Parse allocation log file and return summary with configurable limits.
     *
     * @param logFilePath Path to the log file
     * @param topN Number of largest allocations to include
     * @param topSites Number of top allocation sites to include
     * @return Summary of the log file
     */
    public AllocationLogSummary parseAllocationLog(String logFilePath, int topN, int topSites) {
        AllocationLogSummary.AllocationLogSummaryBuilder builder = AllocationLogSummary.builder()
            .logFilePath(logFilePath);

        try {
            Path path = Paths.get(logFilePath);

            if (!Files.exists(path)) {
                return builder
                    .logFileExists(false)
                    .totalAllocations(0)
                    .ndarrayAllocations(0)
                    .opContextAllocations(0)
                    .totalBytesAllocated(0L)
                    .error("Log file does not exist: " + logFilePath)
                    .build();
            }

            builder.logFileExists(true);

            String content = Files.readString(path);
            List<AllocationEntry> entries = parseEntries(content);

            // Basic counts
            int ndarrayCount = (int) entries.stream()
                .filter(e -> "NDARRAY".equals(e.getAllocationType()))
                .count();
            int opContextCount = entries.size() - ndarrayCount;

            // Total bytes
            long totalBytes = entries.stream()
                .filter(e -> e.getSizeBytes() != null)
                .mapToLong(AllocationEntry::getSizeBytes)
                .sum();

            // Allocations by operation
            Map<String, Integer> byOperation = entries.stream()
                .filter(e -> e.getOperation() != null && !e.getOperation().isEmpty())
                .collect(Collectors.groupingBy(
                    AllocationEntry::getOperation,
                    Collectors.summingInt(e -> 1)
                ));

            // Largest allocations
            List<AllocationEntry> largest = entries.stream()
                .filter(e -> e.getSizeBytes() != null)
                .sorted(Comparator.comparingLong(AllocationEntry::getSizeBytes).reversed())
                .limit(topN)
                .collect(Collectors.toList());

            // Top allocation sites (by source location in stack trace)
            Map<String, Integer> allocationSites = new HashMap<>();
            for (AllocationEntry entry : entries) {
                if (entry.getStackTrace() != null && !entry.getStackTrace().isEmpty()) {
                    // Use the first frame (direct allocation site)
                    String site = entry.getStackTrace().get(0);
                    allocationSites.merge(site, 1, Integer::sum);
                }
            }

            Map<String, Integer> topAllocationSites = allocationSites.entrySet().stream()
                .sorted(Map.Entry.<String, Integer>comparingByValue().reversed())
                .limit(topSites)
                .collect(Collectors.toMap(
                    Map.Entry::getKey,
                    Map.Entry::getValue,
                    (e1, e2) -> e1,
                    LinkedHashMap::new
                ));

            // Rate statistics
            AllocationRateStats rateStats = calculateRateStats(entries);

            return builder
                .totalAllocations(entries.size())
                .ndarrayAllocations(ndarrayCount)
                .opContextAllocations(opContextCount)
                .totalBytesAllocated(totalBytes)
                .allocationsByOperation(byOperation)
                .largestAllocations(largest)
                .topAllocationSites(topAllocationSites)
                .rateStats(rateStats)
                .build();

        } catch (IOException e) {
            log.error("Error reading allocation log file: {}", logFilePath, e);
            return builder
                .logFileExists(false)
                .totalAllocations(0)
                .ndarrayAllocations(0)
                .opContextAllocations(0)
                .totalBytesAllocated(0L)
                .error("Error reading file: " + e.getMessage())
                .build();
        } catch (Exception e) {
            log.error("Error parsing allocation log: {}", logFilePath, e);
            return builder
                .logFileExists(true)
                .totalAllocations(0)
                .ndarrayAllocations(0)
                .opContextAllocations(0)
                .totalBytesAllocated(0L)
                .error("Error parsing log: " + e.getMessage())
                .build();
        }
    }

    /**
     * Parse all allocation entries from log content.
     */
    private List<AllocationEntry> parseEntries(String content) {
        List<AllocationEntry> entries = new ArrayList<>();

        // Split by allocation separator
        String[] blocks = content.split("========================================");

        for (String block : blocks) {
            if (block.trim().isEmpty()) {
                continue;
            }

            AllocationEntry entry = parseEntry(block);
            if (entry != null) {
                entries.add(entry);
            }
        }

        return entries;
    }

    /**
     * Parse a single allocation entry block.
     */
    private AllocationEntry parseEntry(String block) {
        AllocationEntry.AllocationEntryBuilder builder = AllocationEntry.builder();

        try {
            // Determine allocation type
            Matcher ndarrayMatcher = NDARRAY_ALLOCATION_PATTERN.matcher(block);
            Matcher opContextMatcher = OPCONTEXT_ALLOCATION_PATTERN.matcher(block);

            if (ndarrayMatcher.find()) {
                builder.allocationType("NDARRAY");
                builder.allocationNumber(Long.parseLong(ndarrayMatcher.group(1)));
            } else if (opContextMatcher.find()) {
                builder.allocationType("OPCONTEXT");
                builder.allocationNumber(Long.parseLong(opContextMatcher.group(1)));
            } else {
                return null; // Not a valid allocation entry
            }

            // Extract pointer
            Matcher ptrMatcher = PTR_PATTERN.matcher(block);
            if (ptrMatcher.find()) {
                builder.pointer(ptrMatcher.group(1));
            }

            // Extract size (NDArray only)
            Matcher sizeMatcher = SIZE_PATTERN.matcher(block);
            if (sizeMatcher.find()) {
                builder.sizeBytes(Long.parseLong(sizeMatcher.group(1)));
            }

            // Extract data type (NDArray only)
            Matcher dtypeMatcher = DTYPE_PATTERN.matcher(block);
            if (dtypeMatcher.find()) {
                builder.dataType(dtypeMatcher.group(1));
            }

            // Extract shape (NDArray only)
            Matcher shapeMatcher = SHAPE_PATTERN.matcher(block);
            if (shapeMatcher.find()) {
                String shapeStr = shapeMatcher.group(1);
                List<Long> shape = Arrays.stream(shapeStr.split(","))
                    .map(String::trim)
                    .map(Long::parseLong)
                    .collect(Collectors.toList());
                builder.shape(shape);
            }

            // Extract is_view (NDArray only)
            Matcher isViewMatcher = IS_VIEW_PATTERN.matcher(block);
            if (isViewMatcher.find()) {
                builder.isView(Boolean.parseBoolean(isViewMatcher.group(1)));
            }

            // Extract operation
            Matcher operationMatcher = OPERATION_PATTERN.matcher(block);
            if (operationMatcher.find()) {
                builder.operation(operationMatcher.group(1).trim());
            }

            // Extract num inputs (OpContext only)
            Matcher numInputsMatcher = NUM_INPUTS_PATTERN.matcher(block);
            if (numInputsMatcher.find()) {
                builder.numInputs(Integer.parseInt(numInputsMatcher.group(1)));
            }

            // Extract num outputs (OpContext only)
            Matcher numOutputsMatcher = NUM_OUTPUTS_PATTERN.matcher(block);
            if (numOutputsMatcher.find()) {
                builder.numOutputs(Integer.parseInt(numOutputsMatcher.group(1)));
            }

            // Extract timestamp
            Matcher timestampMatcher = TIMESTAMP_PATTERN.matcher(block);
            if (timestampMatcher.find()) {
                builder.timestamp(Long.parseLong(timestampMatcher.group(1)));
            }

            // Extract thread ID
            Matcher threadMatcher = THREAD_PATTERN.matcher(block);
            if (threadMatcher.find()) {
                builder.threadId(threadMatcher.group(1));
            }

            // Extract stack trace
            List<String> stackTrace = new ArrayList<>();
            String[] lines = block.split("\n");
            boolean inStackTrace = false;

            for (String line : lines) {
                if (line.contains("C++ STACK TRACE:") || line.contains("STACK TRACE:")) {
                    inStackTrace = true;
                    continue;
                }

                if (inStackTrace) {
                    if (line.trim().startsWith("---") || line.trim().startsWith("===")) {
                        break;
                    }
                    Matcher frameMatcher = STACK_FRAME_PATTERN.matcher(line);
                    if (frameMatcher.find()) {
                        stackTrace.add(frameMatcher.group(1).trim());
                    }
                }
            }

            builder.stackTrace(stackTrace);
            builder.rawEntry(block);

            return builder.build();

        } catch (Exception e) {
            log.debug("Error parsing allocation entry block", e);
            return null;
        }
    }

    /**
     * Calculate allocation rate statistics.
     */
    private AllocationRateStats calculateRateStats(List<AllocationEntry> entries) {
        if (entries.isEmpty()) {
            return AllocationRateStats.builder()
                .firstAllocationTime(0L)
                .lastAllocationTime(0L)
                .durationMs(0L)
                .allocationsPerSecond(0.0)
                .bytesPerSecond(0.0)
                .mbPerSecond(0.0)
                .build();
        }

        // Find first and last timestamps
        long first = entries.stream()
            .filter(e -> e.getTimestamp() != null)
            .mapToLong(AllocationEntry::getTimestamp)
            .min()
            .orElse(0L);

        long last = entries.stream()
            .filter(e -> e.getTimestamp() != null)
            .mapToLong(AllocationEntry::getTimestamp)
            .max()
            .orElse(0L);

        long durationNs = last - first;
        long durationMs = durationNs / 1_000_000;
        double durationSec = durationNs / 1_000_000_000.0;

        if (durationSec <= 0) {
            durationSec = 0.001; // Avoid division by zero
        }

        long totalBytes = entries.stream()
            .filter(e -> e.getSizeBytes() != null)
            .mapToLong(AllocationEntry::getSizeBytes)
            .sum();

        double allocationsPerSec = entries.size() / durationSec;
        double bytesPerSec = totalBytes / durationSec;
        double mbPerSec = bytesPerSec / (1024.0 * 1024.0);

        return AllocationRateStats.builder()
            .firstAllocationTime(first)
            .lastAllocationTime(last)
            .durationMs(durationMs)
            .allocationsPerSecond(allocationsPerSec)
            .bytesPerSecond(bytesPerSec)
            .mbPerSecond(mbPerSec)
            .build();
    }

    /**
     * Get all allocation entries from a log file (for detailed analysis).
     */
    public List<AllocationEntry> getAllEntries(String logFilePath) {
        try {
            Path path = Paths.get(logFilePath);

            if (!Files.exists(path)) {
                return Collections.emptyList();
            }

            String content = Files.readString(path);
            return parseEntries(content);

        } catch (Exception e) {
            log.error("Error reading all entries from allocation log: {}", logFilePath, e);
            return Collections.emptyList();
        }
    }
}
