/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */
package ai.kompile.event.attribution.domain;

/**
 * Classifies causal relationship types between events in the knowledge graph.
 * These are semantic labels applied to edges during causal chain extraction
 * to distinguish the nature of the causal link.
 */
public enum CausalEdgeType {

    /**
     * Direct causation: X directly causes Y with no intermediary.
     * Example: "The server crash caused the outage."
     */
    CAUSES,

    /**
     * Enabling condition: X is a necessary precondition for Y but does not
     * guarantee Y will happen.
     * Example: "Deploying the code enabled the bug to manifest."
     */
    ENABLES,

    /**
     * Temporal trigger: X triggers Y via a time-based mechanism.
     * Example: "The cron job at 3am triggered the backup."
     */
    TRIGGERS,

    /**
     * Contributing factor: X increases the probability of Y but is not
     * sufficient on its own.
     * Example: "High load contributed to the latency spike."
     */
    CONTRIBUTES_TO,

    /**
     * Preventive relationship: X would normally prevent Y.
     * Useful for counterfactual reasoning ("if the firewall hadn't been
     * disabled, the breach wouldn't have occurred").
     */
    PREVENTS,

    /**
     * Correlation without confirmed causation. The system detected a
     * statistical or temporal association but cannot confirm directionality.
     */
    CORRELATES_WITH,

    /**
     * Influence propagation: X influences Y through an indirect chain,
     * possibly through multiple intermediaries.
     */
    INFLUENCES,

    /**
     * Provenance derivation: Y was derived from or generated by X.
     * Aligns with W3C PROV-DM wasDerivedFrom semantics.
     */
    DERIVED_FROM
}
