/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.pipelines.framework.api.data;

import ai.kompile.pipelines.framework.api.Configuration;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data; // Using Lombok's @Data for getters, setters, equals, hashCode, toString
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.util.Arrays; // For Arrays.equals and Arrays.hashCode
import java.util.Objects;

/**
 * Represents a point in N-dimensional space.
 * It includes coordinates, an optional label, and an optional probability.
 * This class implements {@link Configuration} to indicate it can be part of
 * serializable configurations if used standalone, or just {@link java.io.Serializable}
 * if only ever a value within a {@link Data} object.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Accessors(fluent = true)
public class Point implements Configuration { // Implements Configuration for broader use

    @JsonProperty("dimensions")
    private double[] dimensions;

    @JsonProperty("label")
    private String label;

    @JsonProperty("probability")
    private Double probability;

    /**
     * Creates a 2D point.
     * @param x The x-coordinate.
     * @param y The y-coordinate.
     * @return A new Point instance.
     */
    public static Point newPoint(double x, double y) {
        return Point.builder().dimensions(new double[]{x, y}).build();
    }

    /**
     * Creates a 3D point.
     * @param x The x-coordinate.
     * @param y The y-coordinate.
     * @param z The z-coordinate.
     * @return A new Point instance.
     */
    public static Point newPoint(double x, double y, double z) {
        return Point.builder().dimensions(new double[]{x, y, z}).build();
    }

    /**
     * Creates a 2D point with a label.
     * @param x The x-coordinate.
     * @param y The y-coordinate.
     * @param label The label for the point.
     * @return A new Point instance.
     */
    public static Point newPoint(double x, double y, String label) {
        return Point.builder().dimensions(new double[]{x, y}).label(label).build();
    }

    /**
     * Creates a Point from an array of dimensions.
     * @param dimensions The coordinates of the point.
     * @return A new Point instance.
     */
    public static Point newPoint(double... dimensions) {
        return Point.builder().dimensions(dimensions).build();
    }


    @JsonCreator
    public static Point create(@JsonProperty("dimensions") double[] dimensions,
                               @JsonProperty("label") String label,
                               @JsonProperty("probability") Double probability) {
        return Point.builder()
                .dimensions(dimensions)
                .label(label)
                .probability(probability)
                .build();
    }

    public double x() {
        if (dimensions == null || dimensions.length < 1) {
            throw new IllegalStateException("Point has no x dimension or is not initialized.");
        }
        return dimensions[0];
    }

    public double y() {
        if (dimensions == null || dimensions.length < 2) {
            throw new IllegalStateException("Point has no y dimension or is not 2D+.");
        }
        return dimensions[1];
    }

    public double z() {
        if (dimensions == null || dimensions.length < 3) {
            throw new IllegalStateException("Point has no z dimension or is not 3D+.");
        }
        return dimensions[2];
    }

    public int N() {
        return dimensions == null ? 0 : dimensions.length;
    }

    // Custom equals and hashCode are generated by Lombok's @Data,
    // which handles array fields correctly (Arrays.equals/hashCode).
}