/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ai.kompile.core.mcp.server;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * Configuration for an MCP resource.
 * Resources provide context by exposing data through URI-based access.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class McpResourceConfig {

    /**
     * URI for the resource (supports templates like file://{path})
     */
    private String uri;

    /**
     * Human-readable name for the resource
     */
    private String name;

    /**
     * Description of what this resource provides
     */
    private String description;

    /**
     * MIME type of the resource content
     */
    @Builder.Default
    private String mimeType = "text/plain";

    /**
     * Type of resource provider
     */
    @Builder.Default
    private ResourceType resourceType = ResourceType.STATIC;

    /**
     * Configuration for file-based resources
     */
    private FileResourceConfig fileConfig;

    /**
     * Configuration for HTTP-based resources
     */
    private HttpResourceConfig httpConfig;

    /**
     * Configuration for database-based resources
     */
    private DatabaseResourceConfig databaseConfig;

    /**
     * Static content (for STATIC type)
     */
    private String staticContent;

    /**
     * Whether this resource supports subscriptions
     */
    @Builder.Default
    private boolean supportsSubscription = false;

    /**
     * Whether this resource is enabled
     */
    @Builder.Default
    private boolean enabled = true;

    /**
     * Resource type enumeration
     */
    public enum ResourceType {
        /**
         * Static content stored in configuration
         */
        STATIC,
        /**
         * File-based resource
         */
        FILE,
        /**
         * HTTP endpoint resource
         */
        HTTP,
        /**
         * Database query resource
         */
        DATABASE,
        /**
         * Dynamic resource generated by code
         */
        DYNAMIC
    }

    /**
     * File resource configuration
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FileResourceConfig {
        private String basePath;
        private String pattern; // glob pattern for file matching
        @Builder.Default
        private boolean recursive = false;
        @Builder.Default
        private boolean watchForChanges = false;
    }

    /**
     * HTTP resource configuration
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class HttpResourceConfig {
        private String url;
        @Builder.Default
        private String method = "GET";
        private Map<String, String> headers;
        @Builder.Default
        private int timeoutMs = 30000;
        @Builder.Default
        private int cacheTtlSeconds = 300;
    }

    /**
     * Database resource configuration
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DatabaseResourceConfig {
        private String dataSourceName;
        private String query;
        private Map<String, Object> parameters;
        @Builder.Default
        private String outputFormat = "json"; // json, csv, text
    }
}
