kompile.cli.version=0.1.0-SNAPSHOT
project.version=0.1.0-SNAPSHOT
kompile.app.version=0.1.0-SNAPSHOT
spring.boot.version=3.2.5
spring.ai.version=1.0.0
native.image.plugin.version=0.10.1
maven.compiler.plugin.version=3.13.0
maven.resources.plugin.version=3.3.1
maven.assembly.plugin.version=3.7.1
frontend.maven.plugin.version=1.15.0
os.maven.plugin.version=1.7.1
