#!/usr/bin/env bash
# Run the managed initial crawl profile generated by kompile init-project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
APP_URL="${APP_URL:-http://localhost:8080}"

cd "$PROJECT_DIR"
kompile project workflow-run --id initial-crawl --url "$APP_URL" "$@"
