#!/usr/bin/env bash
# Start the model staging server
# Generated by kompile init-project
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
STAGING_DIR="$PROJECT_DIR/staging"
LOG_DIR="$PROJECT_DIR/data/logs"
PID_DIR="$PROJECT_DIR/data/pids"
MODELS_DIR="$PROJECT_DIR/data/models"
mkdir -p "$LOG_DIR" "$PID_DIR" "$MODELS_DIR/.staging"

PID_FILE="$PID_DIR/staging.pid"
if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "Staging server already running (PID $(cat "$PID_FILE"))"
  exit 1
fi

# Find staging executable (native or JAR)
if [ -x "$STAGING_DIR/kompile-model-staging" ]; then
  CMD="$STAGING_DIR/kompile-model-staging"
elif ls "$STAGING_DIR"/kompile-model-staging*.jar 1>/dev/null 2>&1; then
  JAR=$(ls -t "$STAGING_DIR"/kompile-model-staging*.jar | head -1)
  CMD="java -Xmx4g -jar $JAR"
else
  echo "No staging server found in $STAGING_DIR"
  echo "Install with: kompile install kompile-model-staging"
  exit 1
fi

echo "Starting staging server on port 8090..."
$CMD --server --server.port=8090 \
  --kompile.staging.model-dir="$MODELS_DIR" \
  --kompile.staging.staging-dir="$MODELS_DIR/.staging" \
  > "$LOG_DIR/staging-server.log" 2>&1 &
echo "$!" > "$PID_FILE"
echo "Started staging server (PID $!). Logs: $LOG_DIR/staging-server.log"
