#!/usr/bin/env bash
# Start all kompile services in the correct order
# Generated by kompile init-project
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Starting kompile services ==="
echo ""

# 1. Staging server (model registry)
echo "[1/3] Starting staging server..."
"$SCRIPT_DIR/start-staging.sh" || true
sleep 2

# 2. LLM serving subprocess (inference)
echo "[2/3] Starting LLM serving subprocess..."
"$SCRIPT_DIR/start-serving.sh" || true
sleep 2

# 3. Main application (orchestrator + UI)
echo "[3/3] Starting main application..."
"$SCRIPT_DIR/start-app.sh" || true

echo ""
echo "=== All services started ==="
echo "  Staging:  http://localhost:8090"
echo "  Serving:  http://localhost:8091"
echo "  App:      http://localhost:8080"
echo ""
echo "Stop all:   $SCRIPT_DIR/stop-all.sh"
echo "View logs:  tail -f $(dirname $SCRIPT_DIR)/data/logs/*.log"
