@echo off
REM Start all kompile services
REM Generated by kompile init-project

set SCRIPT_DIR=%~dp0

echo === Starting kompile services ===
echo.

echo [1/3] Starting staging server...
call "%SCRIPT_DIR%start-staging.bat"
timeout /t 2 /nobreak >nul

echo [2/3] Starting LLM serving subprocess...
call "%SCRIPT_DIR%start-serving.bat"
timeout /t 2 /nobreak >nul

echo [3/3] Starting main application...
call "%SCRIPT_DIR%start-app.bat"

echo.
echo === All services started ===
echo   Staging:  http://localhost:8090
echo   Serving:  http://localhost:8091
echo   App:      http://localhost:8080
