#!/usr/bin/env bash
# Start the main kompile application
# Generated by kompile init-project
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
JAR="$PROJECT_DIR/target/kompile-cpu-graph-test-0.1.0-SNAPSHOT.jar"
LOG_DIR="$PROJECT_DIR/data/logs"
PID_DIR="$PROJECT_DIR/data/pids"
mkdir -p "$LOG_DIR" "$PID_DIR"

if [ ! -f "$JAR" ]; then
  echo "JAR not found, building project..."
  cd "$PROJECT_DIR" && mvn package -DskipTests -q
fi

PID_FILE="$PID_DIR/app.pid"
if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "app is already running (PID $(cat "$PID_FILE"))"
  exit 1
fi

echo "Starting application on port 8080..."
java -jar "$JAR" --server.port=8080 > "$LOG_DIR/app.log" 2>&1 &
APP_PID=$!
echo "$APP_PID" > "$PID_FILE"
echo "Started app (PID $APP_PID). Logs: $LOG_DIR/app.log"

echo "Waiting for port 8080..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:8080/actuator/health > /dev/null 2>&1; then
    echo "app is healthy on port 8080"
    exit 0
  fi
  sleep 2
done
echo "Warning: app did not become healthy within 120s (may still be starting)"
echo "Check logs: tail -f $LOG_DIR/app.log"
