@echo off
REM Start the LLM serving subprocess
REM Generated by kompile init-project

set SCRIPT_DIR=%~dp0
set PROJECT_DIR=%SCRIPT_DIR%..
set JAR=%PROJECT_DIR%\target\kompile-cpu-graph-test-0.1.0-SNAPSHOT.jar
set LOG_DIR=%PROJECT_DIR%\data\logs
set PID_DIR=%PROJECT_DIR%\data\pids
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
if not exist "%PID_DIR%" mkdir "%PID_DIR%"

if not exist "%JAR%" (
  echo JAR not found, building project...
  cd /d "%PROJECT_DIR%" && mvn package -DskipTests -q
)

echo Starting serving on port 8091...
start "kompile-serving" /B java -jar "%JAR%" --subprocess=serving --port=8091 --staging-url=http://localhost:8090 > "%LOG_DIR%\serving-subprocess.log" 2>&1
echo Started serving. Logs: %LOG_DIR%\serving-subprocess.log
