@echo off
REM Start the model staging server
REM Generated by kompile init-project

set SCRIPT_DIR=%~dp0
set PROJECT_DIR=%SCRIPT_DIR%..
set STAGING_DIR=%PROJECT_DIR%\staging
set LOG_DIR=%PROJECT_DIR%\data\logs
set MODELS_DIR=%PROJECT_DIR%\data\models
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
if not exist "%MODELS_DIR%\.staging" mkdir "%MODELS_DIR%\.staging"

if exist "%STAGING_DIR%\kompile-model-staging.exe" (
  set CMD="%STAGING_DIR%\kompile-model-staging.exe"
) else (
  for %%f in ("%STAGING_DIR%\kompile-model-staging*.jar") do set CMD=java -Xmx4g -jar "%%f"
)

if not defined CMD (
  echo No staging server found in %STAGING_DIR%
  exit /b 1
)

echo Starting staging server on port 8090...
start "kompile-staging" /B %CMD% --server --server.port=8090 --kompile.staging.model-dir="%MODELS_DIR%" --kompile.staging.staging-dir="%MODELS_DIR%\.staging" > "%LOG_DIR%\staging-server.log" 2>&1
echo Started staging server. Logs: %LOG_DIR%\staging-server.log
