@echo off
REM Start the main kompile application
REM Generated by kompile init-project

set SCRIPT_DIR=%~dp0
set PROJECT_DIR=%SCRIPT_DIR%..
set JAR=%PROJECT_DIR%\target\kompile-cpu-graph-test-0.1.0-SNAPSHOT.jar
set LOG_DIR=%PROJECT_DIR%\data\logs
set PID_DIR=%PROJECT_DIR%\data\pids
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
if not exist "%PID_DIR%" mkdir "%PID_DIR%"

if not exist "%JAR%" (
  echo JAR not found, building project...
  cd /d "%PROJECT_DIR%" && mvn package -DskipTests -q
)

echo Starting app on port 8080...
start "kompile-app" /B java -jar "%JAR%" --server.port=8080 > "%LOG_DIR%\app.log" 2>&1
echo Started app. Logs: %LOG_DIR%\app.log
