#!/usr/bin/env bash
# Stop all kompile services
# Generated by kompile init-project
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PID_DIR="$(dirname "$SCRIPT_DIR")/data/pids"

stopped=0
for pid_file in "$PID_DIR"/*.pid; do
  [ -f "$pid_file" ] || continue
  name=$(basename "$pid_file" .pid)
  pid=$(cat "$pid_file")
  if kill -0 "$pid" 2>/dev/null; then
    echo "Stopping $name (PID $pid)..."
    kill "$pid"
    stopped=$((stopped + 1))
  else
    echo "$name not running (stale PID $pid)"
  fi
  rm -f "$pid_file"
done

if [ $stopped -eq 0 ]; then
  echo "No running services found."
else
  echo "Stopped $stopped service(s)."
fi
