@echo off
REM Stop all kompile services
REM Generated by kompile init-project

echo Stopping all kompile Java processes...
REM This uses window titles set by start-*.bat scripts
taskkill /FI "WINDOWTITLE eq kompile-app" /T /F 2>nul
taskkill /FI "WINDOWTITLE eq kompile-serving" /T /F 2>nul
taskkill /FI "WINDOWTITLE eq kompile-staging" /T /F 2>nul
echo Done.
