#!/usr/bin/env bash
# One-go provisioning: from a filled parameters.env to deployed CodeBuild
# projects for every hostable target.
#   provision.sh CONFIG [build|validation|all]
# Steps: resolve derived values -> preflight (all problems at once) ->
# account bootstrap (buckets/ECR/fleet role) -> GitHub source credentials
# (when configured) -> container images -> reserved fleets -> deploy stacks.
# All derived values are appended to generated-codebuild.env beside CONFIG;
# rerunning is safe (every step is idempotent).
set -euo pipefail
root="$(cd "$(dirname "$0")/../../../.." && pwd)"
here="$root/aws/codebuild/scripts/aws"
config="${1:?Usage: provision.sh CONFIG [build|validation|all] [--plan]}"
shift
kind=build plan=0
for arg in "$@"; do
  case "$arg" in
    build|validation|all) kind="$arg" ;;
    --plan) plan=1 ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

merged="$(cd "$(dirname "$config")" && pwd)/generated-codebuild.env"
cp "$config" "$merged"
printf '\n# --- values below are generated by provision.sh ---\n' >> "$merged"

cfg() { ( set +u; # shellcheck disable=SC1090
          source "$merged"; eval "printf '%s' \"\${$1:-}\"" ); }

echo "== resolve =="
"$here/resolve-config.sh" "$merged" >> "$merged"

echo "== preflight ($kind) =="
"$here/preflight-check.sh" "$merged" "$kind"

if [ "$plan" = 1 ]; then
  echo "== plan: template validation (server-side) =="
  for template in template.yml seed.yml; do
    aws cloudformation validate-template --region "$(cfg AWS_REGION)" \
      --template-body "file://$root/aws/codebuild/$template" >/dev/null
    echo "  $template: valid"
  done
  echo "== plan: account resources =="
  "$here/plan-report.sh" "$merged"
  echo "== plan: stacks ($kind — server-validated change sets, nothing executes) =="
  DEPLOY_PLAN=1 "$here/deploy-all.sh" "$merged" "$kind"
  echo
  echo "PLAN COMPLETE — no resources were created or modified (transient change sets cleaned up)."
  exit 0
fi

echo "== account bootstrap =="
"$here/bootstrap-account.sh" "$merged" >> "$merged"

gh_secret="$(cfg GITHUB_TOKEN_SECRET)"
if [ -n "$gh_secret" ]; then
  if aws secretsmanager describe-secret --region "$(cfg AWS_REGION)" --secret-id "$gh_secret" >/dev/null 2>&1; then
    echo "== github source credentials =="
    "$here/configure-source.sh" "$merged" "$gh_secret"
  else
    echo "WARN: GITHUB_TOKEN_SECRET='$gh_secret' does not exist yet; run:" >&2
    echo "  printf '%s' \"\$TOKEN\" | $here/set-github-token.sh $config $gh_secret" >&2
  fi
fi

echo "== container images =="
"$here/build-images.sh" "$merged" auto

echo "== reserved fleets =="
"$here/create-fleets.sh" "$merged" >> "$merged"

echo "== deploy ($kind) =="
"$here/deploy-all.sh" "$merged" "$kind"

echo
echo "Provisioned. Generated config: $merged"
echo "Start everything:   $here/start-all.sh $config $kind"
echo "Start one target:   $here/start-build.sh $config linux-x86_64 [KOMPILE_REF] [DL4J_REF] [RELEASE_TAG]"
