/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */
package ai.kompile.graph.algorithms.community;

import java.time.Instant;
import java.util.List;

/**
 * Summary of a single community generated by an LLM (or placeholder when LLM is unavailable).
 *
 * @param communityId  dense community identifier in the assignment map
 * @param nodeIds      member node UUIDs (typically a sample if the community is large)
 * @param summary      natural-language summary of the community
 * @param generatedAt  timestamp when the summary was generated
 */
public record CommunitySummary(
        int communityId,
        List<String> nodeIds,
        String summary,
        Instant generatedAt
) {}
