#!/usr/bin/env bash
# One-go GCP provisioning for the TPU lanes: from a filled parameters.env to
# runnable Cloud Build configs.
#   provision.sh CONFIG
# Steps: resolve derived values -> preflight -> enable APIs -> Artifact
# Registry repo -> artifact bucket -> build service account + IAM -> builder
# image (reuses aws/codebuild/images/tpu). Idempotent; derived values append
# to generated-cloudbuild-gcp.env beside CONFIG.
set -euo pipefail
root="$(cd "$(dirname "$0")/../../.." && pwd)"
here="$root/gcp/cloudbuild/scripts"
config="${1:?Usage: provision.sh CONFIG [--plan]}"
plan=0
[ "${2:-}" = --plan ] && plan=1

merged="$(cd "$(dirname "$config")" && pwd)/generated-cloudbuild-gcp.env"
cp "$config" "$merged"
printf '\n# --- values below are generated by provision.sh ---\n' >> "$merged"

echo "== resolve =="
"$here/resolve-config.sh" "$merged" >> "$merged"

echo "== preflight =="
"$here/preflight-check.sh" "$merged"

# shellcheck disable=SC1090
source "$merged"
proj=(--project "$GCP_PROJECT_ID")
prefix="${NAME_PREFIX:-kompile}"

if [ "$plan" = 1 ]; then
  echo "== plan (read-only; nothing is created) =="
  line() { printf '  %-58s %s\n' "$1" "$2"; }
  for api in cloudbuild artifactregistry tpu secretmanager storage logging; do
    if [ -n "$(gcloud services list --enabled "${proj[@]}" \
          --filter="config.name:${api}.googleapis.com" --format='value(config.name)' 2>/dev/null)" ]; then
      line "API ${api}.googleapis.com" "enabled"
    else
      line "API ${api}.googleapis.com" "WOULD ENABLE"
    fi
  done
  if gcloud artifacts repositories describe "$AR_REPOSITORY" "${proj[@]}" --location "$GCP_REGION" >/dev/null 2>&1; then
    line "Artifact Registry $AR_REPOSITORY" "exists"
  else
    line "Artifact Registry $AR_REPOSITORY" "WOULD CREATE"
  fi
  if gcloud storage buckets describe "gs://$ARTIFACT_BUCKET" "${proj[@]}" >/dev/null 2>&1; then
    line "bucket gs://$ARTIFACT_BUCKET" "exists"
  else
    line "bucket gs://$ARTIFACT_BUCKET" "WOULD CREATE"
  fi
  if gcloud iam service-accounts describe "$SERVICE_ACCOUNT_EMAIL" "${proj[@]}" >/dev/null 2>&1; then
    line "service account $SERVICE_ACCOUNT_EMAIL" "exists"
  else
    line "service account $SERVICE_ACCOUNT_EMAIL" "WOULD CREATE"
  fi
  if gcloud artifacts docker images describe "$BUILDER_IMAGE" "${proj[@]}" >/dev/null 2>&1; then
    line "builder image $BUILDER_IMAGE" "pushed"
  else
    line "builder image $BUILDER_IMAGE" "WOULD BUILD + PUSH"
  fi
  if [ -n "${GITHUB_RELEASE_TOKEN_SECRET:-}" ]; then
    if gcloud secrets describe "$GITHUB_RELEASE_TOKEN_SECRET" "${proj[@]}" >/dev/null 2>&1; then
      line "secret $GITHUB_RELEASE_TOKEN_SECRET" "exists"
    else
      line "secret $GITHUB_RELEASE_TOKEN_SECRET" "MISSING (wizard stores it)"
    fi
  fi
  echo
  echo "PLAN COMPLETE — no resources were created or modified."
  exit 0
fi

echo "== enable APIs =="
gcloud services enable "${proj[@]}" \
  cloudbuild.googleapis.com artifactregistry.googleapis.com tpu.googleapis.com \
  secretmanager.googleapis.com storage.googleapis.com logging.googleapis.com

echo "== artifact registry =="
gcloud artifacts repositories describe "$AR_REPOSITORY" "${proj[@]}" \
    --location "$GCP_REGION" >/dev/null 2>&1 \
  || gcloud artifacts repositories create "$AR_REPOSITORY" "${proj[@]}" \
       --location "$GCP_REGION" --repository-format docker >/dev/null

echo "== artifact bucket =="
gcloud storage buckets describe "gs://$ARTIFACT_BUCKET" "${proj[@]}" >/dev/null 2>&1 \
  || gcloud storage buckets create "gs://$ARTIFACT_BUCKET" "${proj[@]}" \
       --location "$GCP_REGION" --uniform-bucket-level-access \
       --public-access-prevention >/dev/null

echo "== build service account =="
sa="$SERVICE_ACCOUNT_EMAIL"
sa_name="${sa%%@*}"
gcloud iam service-accounts describe "$sa" "${proj[@]}" >/dev/null 2>&1 \
  || gcloud iam service-accounts create "$sa_name" "${proj[@]}" \
       --display-name "kompile Cloud Build (TPU lanes)" >/dev/null
for role in roles/tpu.admin roles/logging.logWriter roles/iam.serviceAccountUser roles/secretmanager.secretAccessor; do
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member "serviceAccount:$sa" --role "$role" --condition=None >/dev/null
done
gcloud storage buckets add-iam-policy-binding "gs://$ARTIFACT_BUCKET" "${proj[@]}" \
  --member "serviceAccount:$sa" --role roles/storage.objectAdmin >/dev/null
gcloud artifacts repositories add-iam-policy-binding "$AR_REPOSITORY" "${proj[@]}" \
  --location "$GCP_REGION" --member "serviceAccount:$sa" \
  --role roles/artifactregistry.reader >/dev/null
# The submitting identity must be allowed to run builds AS the custom SA.
account="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -n1)"
case "$account" in
  *gserviceaccount.com) member="serviceAccount:$account" ;;
  *) member="user:$account" ;;
esac
gcloud iam service-accounts add-iam-policy-binding "$sa" "${proj[@]}" \
  --member "$member" --role roles/iam.serviceAccountUser >/dev/null

echo "== builder image (reuses aws/codebuild/images/tpu) =="
gcloud builds submit "$root/aws/codebuild/images/tpu" "${proj[@]}" \
  --config "$root/gcp/cloudbuild/cloudbuild-image.yaml" \
  --substitutions "^~^_IMAGE=${BUILDER_IMAGE}~_GRAALVM_ARCHIVE_URL=${GRAALVM_ARCHIVE_URL}~_JDK11_ARCHIVE_URL=${JDK11_ARCHIVE_URL}~_PJRT_PLUGIN_URL=${PJRT_PLUGIN_URL:-}"

echo
echo "Provisioned. Generated config: $merged"
echo "TPU backend build:  $here/start-build.sh $config build [DL4J_REF] [RELEASE_TAG]"
echo "TPU hardware smoke: $here/start-build.sh $config smoke [DL4J_REF] [RELEASE_TAG]"
