cmake_minimum_required(VERSION 3.19)
if(NOT DEFINED MODE OR NOT DEFINED INPUT OR NOT DEFINED VARIANT)
  message(FATAL_ERROR "MODE, INPUT, and VARIANT are required")
endif()
if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "input does not exist: ${INPUT}")
endif()
file(READ "${INPUT}" JSON)
function(jget OUT)
  string(JSON VALUE ERROR_VARIABLE ERROR GET "${JSON}" ${ARGN})
  if(ERROR)
    message(FATAL_ERROR "missing or invalid JSON field ${ARGN}: ${ERROR}")
  endif()
  set(${OUT} "${VALUE}" PARENT_SCOPE)
endfunction()
function(pget OUT)
  string(JSON VALUE ERROR_VARIABLE ERROR GET "${PROVIDER_JSON}" ${ARGN})
  if(ERROR)
    message(FATAL_ERROR "missing or invalid provider.json field ${ARGN}: ${ERROR}")
  endif()
  set(${OUT} "${VALUE}" PARENT_SCOPE)
endfunction()
function(expect VALUE EXPECTED LABEL)
  if(NOT "${VALUE}" STREQUAL "${EXPECTED}")
    message(FATAL_ERROR "${LABEL}: expected '${EXPECTED}', got '${VALUE}'")
  endif()
endfunction()
function(jarray OUT)
  string(JSON COUNT ERROR_VARIABLE ERROR LENGTH "${JSON}" ${ARGN})
  if(ERROR OR COUNT LESS 1)
    message(FATAL_ERROR "missing or empty JSON array ${ARGN}")
  endif()
  math(EXPR LAST "${COUNT}-1")
  set(VALUES)
  foreach(I RANGE 0 ${LAST})
    jget(V ${ARGN} ${I})
    if(V STREQUAL "")
      message(FATAL_ERROR "empty value in JSON array ${ARGN}")
    endif()
    list(APPEND VALUES "${V}")
  endforeach()
  set(${OUT} "${VALUES}" PARENT_SCOPE)
endfunction()

if(MODE STREQUAL "config")
  if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required for config mode")
  endif()
  jget(V formatVersion)
  expect("${V}" "1" "unsupported accelerator config")
  jget(V offlineOnly)
  expect("${V}" "ON" "accelerator config is not offline-only")
  jget(APP application)
  expect("${APP}" "ai.kompile.chat.local.android" "wrong application identity")
  jget(V graphReasoning androidNativeAotStatus)
  expect("${V}" "built-and-verified" "graph native AOT is not verified")
  jget(V graphReasoning jniTransport)
  expect("${V}" "JavaCPP" "graph JNI transport")
  jget(V graphReasoning minSdk)
  expect("${V}" "28" "graph minimum SDK")
  jget(V graphReasoning androidRuntime)
  expect("${V}" "stock-GraalVM-native-AOT-C-ABI-v1" "graph runtime")
  jarray(GRAPH_LIBS graphReasoning androidNativeLibraries)
  list(SORT GRAPH_LIBS)
  expect("${GRAPH_LIBS}" "libjnikompile_graph.so;libkompile_reasoning_android.so" "graph native library set")

  string(JSON TYPE ERROR_VARIABLE ERROR TYPE "${JSON}" variants ${VARIANT})
  if(ERROR OR NOT TYPE STREQUAL "OBJECT")
    message(FATAL_ERROR "accelerator config has no object variant: ${VARIANT}")
  endif()
  foreach(PAIR "deviceOnly;ON" "aotOnly;ON" "allowHostFallback;OFF")
    list(GET PAIR 0 KEY)
    list(GET PAIR 1 EXPECTED)
    jget(V variants ${VARIANT} ${KEY})
    expect("${V}" "${EXPECTED}" "invalid fail-closed policy ${KEY}")
  endforeach()
  jget(FLAVOR variants ${VARIANT} gradleFlavor)
  expect("${FLAVOR}" "${VARIANT}" "Gradle flavor")
  jget(RUNTIME_AAR variants ${VARIANT} runtimeAar)
  jget(RELEASE_COMPONENT variants ${VARIANT} releaseSelector component)
  expect("${RELEASE_COMPONENT}" "runtime" "release selector component")
  jget(RELEASE_PACKAGE_ROLE variants ${VARIANT} releaseSelector packageRole)
  expect("${RELEASE_PACKAGE_ROLE}" "android-aar" "release selector packageRole")
  jget(RELEASE_PLATFORM variants ${VARIANT} releaseSelector platform)
  jget(RELEASE_VARIANT variants ${VARIANT} releaseSelector variant)
  foreach(VALUE IN ITEMS RELEASE_PLATFORM RELEASE_VARIANT)
    if(NOT "${${VALUE}}" MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$")
      message(FATAL_ERROR "unsafe release selector value in ${VALUE}")
    endif()
  endforeach()
  jget(BACKEND variants ${VARIANT} requiredBackend)
  jget(MIN_SDK variants ${VARIANT} minSdk)
  if(NOT MIN_SDK MATCHES "^[0-9]+$" OR MIN_SDK LESS 28 OR MIN_SDK GREATER 35)
    message(FATAL_ERROR "invalid variant minimum SDK: ${MIN_SDK}")
  endif()
  jarray(REQUIRED_LIBS variants ${VARIANT} requiredNativeLibraries)
  jarray(FORBIDDEN_LIBS variants ${VARIANT} forbiddenLibraries)
  set(DSP_SERVICE "")
  if(VARIANT STREQUAL "vulkan")
    expect("${MIN_SDK}" "28" "Vulkan minimum SDK")
    jget(GPU_TARGET variants ${VARIANT} requiredGpuTarget)
    expect("${GPU_TARGET}" "VULKAN" "Vulkan GPU target")
    set(PACKAGE_SUFFIX vulkan)
    set(PROVIDER vulkan-gpu)
    set(TARGET_PROFILE android-arm64-vulkan)
  elseif(VARIANT STREQUAL "hexagon")
    expect("${MIN_SDK}" "28" "Hexagon minimum SDK")
    jget(DSP_SERVICE variants ${VARIANT} dspServiceLibrary)
    expect("${DSP_SERVICE}" "libsdx_hexagon_runtime_skel.so"
        "Hexagon DSP service library")
    list(FIND REQUIRED_LIBS "${DSP_SERVICE}" DSP_SERVICE_INDEX)
    if(DSP_SERVICE_INDEX LESS 0)
      message(FATAL_ERROR
          "Hexagon DSP service is not in requiredNativeLibraries")
    endif()
    set(GPU_TARGET "")
    set(PACKAGE_SUFFIX hexagon)
    set(PROVIDER hexagon-htp)
    set(TARGET_PROFILE android-arm64-hexagon-htp)
  elseif(VARIANT STREQUAL "tensorG3")
    expect("${MIN_SDK}" "31" "Tensor G3 minimum SDK")
    jget(SYSTEM_DEP variants ${VARIANT} requiredSystemDependency)
    expect("${SYSTEM_DEP}" "libneuralnetworks.so" "Tensor G3 system dependency")
    jget(V variants ${VARIANT} quantization)
    expect("${V}" "int8-per-tensor" "Tensor G3 quantization scheme")
    jget(V variants ${VARIANT} quantizedMatmulInputs)
    expect("${V}" "5" "Tensor G3 quantized matmul arity")
    jget(V variants ${VARIANT} scaleDtype)
    expect("${V}" "FLOAT32" "Tensor G3 scale dtype")
    set(GPU_TARGET "")
    set(PACKAGE_SUFFIX tensorg3)
    set(PROVIDER google-tensor-g3-nnapi)
    set(TARGET_PROFILE android-arm64-nnapi-accelerator)
  elseif(VARIANT STREQUAL "tensorG5")
    expect("${MIN_SDK}" "28" "Tensor G5 minimum SDK")
    set(GPU_TARGET "")
    set(PACKAGE_SUFFIX tensorg5)
    set(PROVIDER google-tensor-g5)
    set(TARGET_PROFILE android-arm64-google-tensor-g5)
  else()
    message(FATAL_ERROR "unsupported APK variant: ${VARIANT}")
  endif()
  foreach(VALUE IN ITEMS RUNTIME_AAR BACKEND PACKAGE_SUFFIX PROVIDER TARGET_PROFILE DSP_SERVICE)
    if("${${VALUE}}" MATCHES "[\r\n=]")
      message(FATAL_ERROR "unsafe config value in ${VALUE}")
    endif()
  endforeach()
  string(REPLACE ";" "," REQUIRED_CSV "${REQUIRED_LIBS}")
  string(REPLACE ";" "," FORBIDDEN_CSV "${FORBIDDEN_LIBS}")
  file(WRITE "${OUTPUT}"
    "APPLICATION=${APP}\nPACKAGE_SUFFIX=${PACKAGE_SUFFIX}\nFLAVOR=${FLAVOR}\n"
    "RUNTIME_AAR=${RUNTIME_AAR}\nBACKEND=${BACKEND}\nGPU_TARGET=${GPU_TARGET}\n"
    "RELEASE_COMPONENT=${RELEASE_COMPONENT}\nRELEASE_PACKAGE_ROLE=${RELEASE_PACKAGE_ROLE}\n"
    "RELEASE_PLATFORM=${RELEASE_PLATFORM}\nRELEASE_VARIANT=${RELEASE_VARIANT}\n"
    "MIN_SDK=${MIN_SDK}\nPROVIDER=${PROVIDER}\nTARGET_PROFILE=${TARGET_PROFILE}\n"
    "DSP_SERVICE=${DSP_SERVICE}\n"
    "REQUIRED_LIBS=${REQUIRED_CSV}\nFORBIDDEN_LIBS=${FORBIDDEN_CSV}\n")
elseif(MODE STREQUAL "assets")
  jget(V formatVersion)
  expect("${V}" "1" "bad asset manifest version")
  jget(V offlineOnly)
  expect("${V}" "ON" "asset manifest permits online use")
  jget(V networkPermissionRequired)
  expect("${V}" "ON" "asset manifest omits required Hugging Face discovery network access")
  jget(V graphRuntime androidMode)
  expect("${V}" "stock-graalvm-aot-javacpp" "graph Android mode")
  jget(V graphRuntime minimumSdk)
  expect("${V}" "28" "graph minimum SDK")
  jarray(LIBS graphRuntime nativeLibraries)
  list(SORT LIBS)
  expect("${LIBS}" "libjnikompile_graph.so;libkompile_reasoning_android.so" "asset graph libraries")
  jget(V modelSlots ${VARIANT} deviceOnly)
  expect("${V}" "ON" "model slot is not device-only")
  jget(V modelSlots ${VARIANT} aotOnly)
  expect("${V}" "ON" "model slot is not AOT-only")
  jget(V modelSlots ${VARIANT} allowHostFallback)
  expect("${V}" "OFF" "model slot permits host fallback")
  if(NOT DEFINED EXPECTED_BACKEND)
    message(FATAL_ERROR "EXPECTED_BACKEND is required")
  endif()
  jget(V modelSlots ${VARIANT} backend)
  expect("${V}" "${EXPECTED_BACKEND}" "model slot backend")
  if(VARIANT STREQUAL "vulkan")
    jget(V modelSlots ${VARIANT} gpuTarget)
    expect("${V}" "VULKAN" "Vulkan model slot GPU target")
  elseif(VARIANT STREQUAL "tensorG3")
    jget(V modelSlots ${VARIANT} quantization)
    expect("${V}" "int8-per-tensor" "Tensor G3 asset quantization scheme")
    jget(V modelSlots ${VARIANT} quantizedMatmulInputs)
    expect("${V}" "5" "Tensor G3 asset quantized matmul arity")
    jget(V modelSlots ${VARIANT} scaleDtype)
    expect("${V}" "FLOAT32" "Tensor G3 asset scale dtype")
  endif()
  string(JSON COUNT ERROR_VARIABLE ERROR LENGTH "${JSON}" assets)
  if(ERROR)
    message(FATAL_ERROR "assets must be an array")
  endif()
  if(COUNT GREATER 0)
    math(EXPR LAST "${COUNT}-1")
    foreach(I RANGE 0 ${LAST})
      jget(PATH assets ${I} path)
      jget(SHA assets ${I} sha256)
      string(LENGTH "${SHA}" SHA_LENGTH)
      if(PATH STREQUAL "" OR PATH MATCHES "(^/|(^|/)\\.\\.(/|$)|\\\\)" OR
         NOT SHA_LENGTH EQUAL 64 OR NOT SHA MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "unsafe asset record at index ${I}")
      endif()
      if(NOT DEFINED ASSET_ROOT OR NOT EXISTS "${ASSET_ROOT}/${PATH}")
        message(FATAL_ERROR "declared offline asset missing: assets/${PATH}")
      endif()
      file(SHA256 "${ASSET_ROOT}/${PATH}" ACTUAL)
      if(NOT ACTUAL STREQUAL SHA)
        message(FATAL_ERROR "offline asset checksum mismatch: assets/${PATH}")
      endif()
    endforeach()
  endif()
elseif(MODE STREQUAL "binding")
  if(NOT DEFINED PROVIDER_INPUT OR PROVIDER_INPUT STREQUAL "" OR
     NOT EXISTS "${PROVIDER_INPUT}")
    message(FATAL_ERROR "provider.json is required for every accelerator runtime")
  endif()
  file(READ "${PROVIDER_INPUT}" PROVIDER_JSON)

  jget(V formatVersion)
  expect("${V}" "1" "unsupported binding manifest")
  jget(V platform androidAbi)
  expect("${V}" "arm64-v8a" "binding Android ABI")
  if(VARIANT STREQUAL "vulkan")
    set(EXPECTED_PROVIDER_ID "sdx.vulkan.v1")
    set(EXPECTED_ARTIFACT_FORMAT "sdx-vulkan-plan")
    set(EXPECTED_TARGET_SOC "Android_Vulkan_1_1")
    set(EXPECTED_PROVIDER_RUNTIME "libnd4jvulkan.so")
  elseif(VARIANT STREQUAL "hexagon")
    set(EXPECTED_PROVIDER_ID "sdx.hexagon-htp.v1")
    set(EXPECTED_ARTIFACT_FORMAT "sdx-htp-context")
    set(EXPECTED_TARGET_SOC "SM8650")
    set(EXPECTED_PROVIDER_RUNTIME "libnd4jhexagon.so")
  elseif(VARIANT STREQUAL "tensorG3")
    set(EXPECTED_PROVIDER_ID "sdx.nnapi-tensor-g3.v1")
    set(EXPECTED_ARTIFACT_FORMAT "sdx-nnapi-plan")
    set(EXPECTED_TARGET_SOC "Tensor_G3")
    set(EXPECTED_PROVIDER_RUNTIME "libnd4jnnapi.so")
  elseif(VARIANT STREQUAL "tensorG5")
    set(EXPECTED_PROVIDER_ID "sdx.litert-tensor-g5.v1")
    set(EXPECTED_ARTIFACT_FORMAT "sdx-litert-model")
    set(EXPECTED_TARGET_SOC "Tensor_G5")
    set(EXPECTED_PROVIDER_RUNTIME "liblitert-lm.so")
  else()
    message(FATAL_ERROR "unsupported provider contract variant: ${VARIANT}")
  endif()

  foreach(PAIR
      "id;${EXPECTED_PROVIDER_ID}"
      "abiVersion;1"
      "artifactFormat;${EXPECTED_ARTIFACT_FORMAT}"
      "artifactFormatVersion;1"
      "defaultTargetSoc;${EXPECTED_TARGET_SOC}"
      "requiresAotArtifact;ON"
      "allowRuntimeJit;OFF"
      "allowCpuFallback;OFF")
    list(GET PAIR 0 KEY)
    list(GET PAIR 1 EXPECTED)
    jget(V platformProvider ${KEY})
    expect("${V}" "${EXPECTED}" "binding platform provider ${KEY}")
  endforeach()
  foreach(PAIR
      "formatVersion;1"
      "coreAbi;1"
      "providerId;${EXPECTED_PROVIDER_ID}"
      "providerAbi;1"
      "artifactFormat;${EXPECTED_ARTIFACT_FORMAT}"
      "artifactFormatVersion;1"
      "platformId;android-arm64"
      "architecture;arm64"
      "defaultTargetSoc;${EXPECTED_TARGET_SOC}"
      "runtimeLibrary;${EXPECTED_PROVIDER_RUNTIME}"
      "requiresAotArtifact;ON"
      "allowRuntimeJit;OFF"
      "allowCpuFallback;OFF")
    list(GET PAIR 0 KEY)
    list(GET PAIR 1 EXPECTED)
    pget(V ${KEY})
    expect("${V}" "${EXPECTED}" "provider contract ${KEY}")
  endforeach()

  if(VARIANT STREQUAL "tensorG5")
    jget(V provider)
    expect("${V}" "litert-lm" "Tensor G5 provider")
    jget(V variant)
    expect("${V}" "google-tensor-g5" "Tensor G5 binding variant")
    jget(V runtimeLibrary)
    expect("${V}" "liblitert-lm.so" "Tensor G5 runtime")
    jget(V modelFormat)
    expect("${V}" "litertlm" "Tensor G5 model format")
    foreach(PAIR "deviceOnly;ON" "aotOnly;ON" "hostFallback;OFF")
      list(GET PAIR 0 KEY)
      list(GET PAIR 1 EXPECTED)
      jget(V executionPolicy ${KEY})
      expect("${V}" "${EXPECTED}" "Tensor G5 execution policy ${KEY}")
    endforeach()
  else()
    if(VARIANT STREQUAL "tensorG3")
      set(EXPECTED_VARIANT tensor-g3)
      set(EXPECTED_RUNTIME libnd4jnnapi.so)
    elseif(VARIANT STREQUAL "vulkan")
      set(EXPECTED_VARIANT vulkan)
      set(EXPECTED_RUNTIME libnd4jvulkan.so)
    elseif(VARIANT STREQUAL "hexagon")
      set(EXPECTED_VARIANT hexagon)
      set(EXPECTED_RUNTIME libnd4jhexagon.so)
      jget(V dspService domain)
      expect("${V}" "cdsp" "Hexagon DSP service domain")
      jget(V dspService module)
      expect("${V}" "sdx_hexagon_runtime" "Hexagon DSP service module")
      jget(V dspService library)
      expect("${V}" "libsdx_hexagon_runtime_skel.so"
          "Hexagon DSP service library")
      jget(V dspService androidAarEntry)
      expect("${V}" "jni/arm64-v8a/libsdx_hexagon_runtime_skel.so"
          "Hexagon DSP service AAR entry")
      jget(V dspService architecture)
      expect("${V}" "hexagon-v75" "Hexagon DSP service architecture")
      jget(V dspService searchPathEnvironment)
      expect("${V}" "DSP_LIBRARY_PATH"
          "Hexagon DSP service search path")
      jget(V dspService requiresLegacyNativePackaging)
      expect("${V}" "ON" "Hexagon DSP service extraction policy")
    else()
      message(FATAL_ERROR "unsupported binding variant")
    endif()
    jget(V variant)
    expect("${V}" "${EXPECTED_VARIANT}" "binding variant")
    jget(V runtimeLibrary)
    expect("${V}" "${EXPECTED_RUNTIME}" "binding runtime")
  endif()
else()
  message(FATAL_ERROR "unsupported MODE: ${MODE}")
endif()
