/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */
package ai.kompile.cli.main.graph;

import ai.kompile.cli.common.http.KompileHttpClient;
import ai.kompile.cli.main.app.AppClientMixin;
import ai.kompile.cli.main.app.OutputFormatter;
import com.fasterxml.jackson.databind.JsonNode;
import picocli.CommandLine;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;

/**
 * {@code kompile graph proposals} — review and manage triple proposals
 * generated by graph extraction jobs.
 *
 * <p>Examples:
 * <pre>
 *   # List pending proposals for a job
 *   kompile graph proposals list --job-id abc-123 --status PENDING
 *
 *   # Accept a specific proposal
 *   kompile graph proposals accept proposal-456
 *
 *   # Reject a proposal with reason
 *   kompile graph proposals reject proposal-456 --reason "Incorrect relationship"
 *
 *   # Bulk accept all pending proposals for a job
 *   kompile graph proposals bulk-accept --job-id abc-123
 *
 *   # Create a manual triple proposal
 *   kompile graph proposals manual --fact-sheet-id 42 \
 *       --subject "Albert Einstein" --subject-type PERSON \
 *       --predicate "developed" \
 *       --object "Theory of Relativity" --object-type CONCEPT
 * </pre>
 */
@CommandLine.Command(
        name = "proposals",
        description = "Review and manage graph extraction proposals",
        subcommands = {
                GraphProposalsCommand.ListCmd.class,
                GraphProposalsCommand.ShowCmd.class,
                GraphProposalsCommand.AcceptCmd.class,
                GraphProposalsCommand.RejectCmd.class,
                GraphProposalsCommand.BulkAcceptCmd.class,
                GraphProposalsCommand.BulkRejectCmd.class,
                GraphProposalsCommand.ManualCmd.class
        },
        mixinStandardHelpOptions = true
)
public class GraphProposalsCommand implements Callable<Integer> {

    @Override
    public Integer call() {
        new CommandLine(this).usage(System.out);
        return 0;
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals list
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "list", description = "List triple proposals",
            mixinStandardHelpOptions = true)
    static class ListCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Option(names = "--job-id", description = "Filter by job ID")
        private String jobId;

        @CommandLine.Option(names = {"--fact-sheet-id", "-f"}, description = "Filter by fact sheet ID")
        private Long factSheetId;

        @CommandLine.Option(names = "--status",
                description = "Filter by status: PENDING, ACCEPTED, REJECTED")
        private String status;

        @CommandLine.Option(names = "--query", description = "Search text in proposals")
        private String query;

        @CommandLine.Option(names = "--page", defaultValue = "0", description = "Page number")
        private int page;

        @CommandLine.Option(names = "--size", defaultValue = "20", description = "Page size")
        private int size;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                StringBuilder url = new StringBuilder("/api/knowledge-graph/builder/proposals?page=")
                        .append(page).append("&size=").append(size);
                if (jobId != null) url.append("&jobId=").append(jobId);
                if (factSheetId != null) url.append("&factSheetId=").append(factSheetId);
                if (status != null) url.append("&status=").append(status);
                if (query != null) url.append("&query=").append(
                        java.net.URLEncoder.encode(query, java.nio.charset.StandardCharsets.UTF_8));

                String response = client.getString(url.toString());
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                    return 0;
                }
                JsonNode result = client.getObjectMapper().readTree(response);
                JsonNode content = result.has("content") ? result.get("content") : result;
                if (!content.isArray() || content.isEmpty()) {
                    System.out.println("No proposals found.");
                    return 0;
                }
                System.out.println("Triple Proposals:");
                for (JsonNode p : content) {
                    printProposalSummary(p);
                    System.out.println();
                }
                if (result.has("totalElements")) {
                    System.out.println("Total: " + result.path("totalElements").asInt()
                            + " (page " + (page + 1) + "/" + result.path("totalPages").asInt() + ")");
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals show <proposalId>
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "show", description = "Show proposal details",
            mixinStandardHelpOptions = true)
    static class ShowCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Parameters(index = "0", description = "Proposal ID")
        private String proposalId;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                String response = client.getString("/api/knowledge-graph/builder/proposals/" + proposalId);
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                    return 0;
                }
                JsonNode p = client.getObjectMapper().readTree(response);
                printProposalDetail(p);
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals accept <proposalId>
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "accept", description = "Accept a triple proposal",
            mixinStandardHelpOptions = true)
    static class AcceptCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Parameters(index = "0", description = "Proposal ID to accept")
        private String proposalId;

        @CommandLine.Option(names = "--reviewed-by", defaultValue = "cli-user",
                description = "Reviewer name")
        private String reviewedBy;

        @CommandLine.Option(names = "--storage-type",
                description = "Storage type (e.g., JPA, NEO4J)")
        private String storageType;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                StringBuilder url = new StringBuilder("/api/knowledge-graph/builder/proposals/")
                        .append(proposalId).append("/accept?reviewedBy=").append(reviewedBy);
                if (storageType != null) url.append("&storageType=").append(storageType);

                String response = client.postEmpty(url.toString());
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                } else {
                    System.out.println("Accepted proposal: " + proposalId);
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals reject <proposalId>
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "reject", description = "Reject a triple proposal",
            mixinStandardHelpOptions = true)
    static class RejectCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Parameters(index = "0", description = "Proposal ID to reject")
        private String proposalId;

        @CommandLine.Option(names = "--reason", description = "Rejection reason")
        private String reason;

        @CommandLine.Option(names = "--reviewed-by", defaultValue = "cli-user",
                description = "Reviewer name")
        private String reviewedBy;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                Map<String, Object> body = new LinkedHashMap<>();
                if (reason != null) body.put("reason", reason);
                body.put("reviewedBy", reviewedBy);

                String response = client.postString(
                        "/api/knowledge-graph/builder/proposals/" + proposalId + "/reject", body);
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                } else {
                    System.out.println("Rejected proposal: " + proposalId);
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals bulk-accept
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "bulk-accept", description = "Bulk accept multiple proposals",
            mixinStandardHelpOptions = true)
    static class BulkAcceptCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Option(names = "--proposal-ids", split = ",", required = true,
                description = "Comma-separated proposal IDs to accept")
        private List<String> proposalIds;

        @CommandLine.Option(names = "--reviewed-by", defaultValue = "cli-user",
                description = "Reviewer name")
        private String reviewedBy;

        @CommandLine.Option(names = "--storage-type",
                description = "Storage type (e.g., JPA, NEO4J)")
        private String storageType;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                Map<String, Object> body = new LinkedHashMap<>();
                body.put("proposalIds", proposalIds);
                body.put("reviewedBy", reviewedBy);
                if (storageType != null) body.put("storageType", storageType);

                String response = client.postString(
                        "/api/knowledge-graph/builder/proposals/bulk-accept", body);
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                } else {
                    JsonNode result = client.getObjectMapper().readTree(response);
                    System.out.println("Bulk accept complete.");
                    result.fields().forEachRemaining(e -> OutputFormatter.printKv(e.getKey(), e.getValue()));
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals bulk-reject
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "bulk-reject", description = "Bulk reject multiple proposals",
            mixinStandardHelpOptions = true)
    static class BulkRejectCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Option(names = "--proposal-ids", split = ",", required = true,
                description = "Comma-separated proposal IDs to reject")
        private List<String> proposalIds;

        @CommandLine.Option(names = "--reviewed-by", defaultValue = "cli-user",
                description = "Reviewer name")
        private String reviewedBy;

        @CommandLine.Option(names = "--reason", description = "Rejection reason")
        private String reason;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                Map<String, Object> body = new LinkedHashMap<>();
                body.put("proposalIds", proposalIds);
                body.put("reviewedBy", reviewedBy);
                if (reason != null) body.put("reason", reason);

                String response = client.postString(
                        "/api/knowledge-graph/builder/proposals/bulk-reject", body);
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                } else {
                    JsonNode result = client.getObjectMapper().readTree(response);
                    System.out.println("Bulk reject complete.");
                    result.fields().forEachRemaining(e -> OutputFormatter.printKv(e.getKey(), e.getValue()));
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // proposals manual — create a manual triple proposal
    // ═══════════════════════════════════════════════════════════════════════════

    @CommandLine.Command(name = "manual", description = "Create a manual triple proposal",
            mixinStandardHelpOptions = true)
    static class ManualCmd implements Callable<Integer> {
        @CommandLine.Mixin private AppClientMixin app;

        @CommandLine.Option(names = {"--fact-sheet-id", "-f"}, required = true,
                description = "Fact sheet ID")
        private long factSheetId;

        @CommandLine.Option(names = "--subject", required = true,
                description = "Subject entity name")
        private String subjectName;

        @CommandLine.Option(names = "--subject-type", required = true,
                description = "Subject entity type (e.g., PERSON, ORG, CONCEPT)")
        private String subjectType;

        @CommandLine.Option(names = "--predicate", required = true,
                description = "Relationship predicate (e.g., 'works_for', 'developed')")
        private String predicateName;

        @CommandLine.Option(names = "--object", required = true,
                description = "Object entity name")
        private String objectName;

        @CommandLine.Option(names = "--object-type", required = true,
                description = "Object entity type")
        private String objectType;

        @CommandLine.Option(names = "--description",
                description = "Optional description of the relationship")
        private String description;

        @CommandLine.Option(names = "--auto-accept",
                description = "Automatically accept this proposal")
        private boolean autoAccept;

        @Override
        public Integer call() {
            KompileHttpClient client = app.requireClient();
            if (client == null) return 1;
            try {
                Map<String, Object> body = new LinkedHashMap<>();
                body.put("factSheetId", factSheetId);
                body.put("subjectName", subjectName);
                body.put("subjectType", subjectType);
                body.put("predicateName", predicateName);
                body.put("objectName", objectName);
                body.put("objectType", objectType);
                if (description != null) body.put("description", description);
                body.put("autoAccept", autoAccept);

                String response = client.postString(
                        "/api/knowledge-graph/builder/proposals/manual", body);
                if (app.isJsonOutput()) {
                    OutputFormatter.printJson(response);
                    return 0;
                }
                JsonNode p = client.getObjectMapper().readTree(response);
                System.out.println("Manual proposal created.");
                printProposalSummary(p);
                return 0;
            } catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                return 1;
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Formatters
    // ═══════════════════════════════════════════════════════════════════════════

    static void printProposalSummary(JsonNode p) {
        String triple = p.path("subjectName").asText("?") + " [" + p.path("subjectType").asText("") + "]"
                + " --" + p.path("predicateName").asText("?") + "--> "
                + p.path("objectName").asText("?") + " [" + p.path("objectType").asText("") + "]";
        OutputFormatter.printKv("Proposal", p.path("proposalId").asText());
        OutputFormatter.printKv("Triple", triple);
        OutputFormatter.printKv("Status", p.path("status").asText());
        OutputFormatter.printKv("Confidence", String.format("%.0f%%", p.path("confidence").asDouble(0) * 100));
    }

    static void printProposalDetail(JsonNode p) {
        System.out.println("Proposal: " + p.path("proposalId").asText());
        OutputFormatter.printKv("Subject", p.path("subjectName").asText() + " [" + p.path("subjectType").asText() + "]");
        OutputFormatter.printKv("Predicate", p.path("predicateName").asText());
        OutputFormatter.printKv("Object", p.path("objectName").asText() + " [" + p.path("objectType").asText() + "]");
        OutputFormatter.printKv("Confidence", String.format("%.0f%%", p.path("confidence").asDouble(0) * 100));
        OutputFormatter.printKv("Status", p.path("status").asText());
        OutputFormatter.printKv("Job ID", p.path("jobId").asText());
        OutputFormatter.printKv("Fact Sheet", p.path("factSheetId"));
        if (p.has("sourceChunkId") && !p.path("sourceChunkId").isNull()) {
            OutputFormatter.printKv("Source Chunk", p.path("sourceChunkId").asText());
        }
        if (p.has("sourceContext") && !p.path("sourceContext").isNull()) {
            String ctx = p.path("sourceContext").asText();
            OutputFormatter.printKv("Source Context",
                    ctx.length() > 200 ? ctx.substring(0, 200) + "..." : ctx);
        }
        if (p.has("reviewedBy") && !p.path("reviewedBy").isNull()) {
            OutputFormatter.printKv("Reviewed By", p.path("reviewedBy").asText());
        }
        if (p.has("reviewedAt") && !p.path("reviewedAt").isNull()) {
            OutputFormatter.printKv("Reviewed At", p.path("reviewedAt").asText());
        }
        if (p.has("rejectionReason") && !p.path("rejectionReason").isNull()) {
            OutputFormatter.printKv("Rejection Reason", p.path("rejectionReason").asText());
        }
        if (p.has("subjectNodeId") && !p.path("subjectNodeId").isNull()) {
            OutputFormatter.printKv("Subject Node", p.path("subjectNodeId").asText());
        }
        if (p.has("objectNodeId") && !p.path("objectNodeId").isNull()) {
            OutputFormatter.printKv("Object Node", p.path("objectNodeId").asText());
        }
        if (p.has("edgeId") && !p.path("edgeId").isNull()) {
            OutputFormatter.printKv("Edge", p.path("edgeId").asText());
        }
        OutputFormatter.printKv("Created", p.path("createdAt").asText());
    }
}
