/*
 * Copyright 2025 Kompile Inc.
 *
 * Licensed under the Apache License, Version 2.0.
 */
package ai.kompile.cli.common.metrics;

/**
 * Identity and correlation context for a single MCP server tool invocation.
 *
 * <p>One stable server invocation ID per logical server execution. Observations,
 * nested wrappers, polls, and fetches of a cached result must NOT create new
 * invocation contexts — reuse the original. True child executions (subagents,
 * delegated model work) get their own context with {@link #parentInvocationId}
 * pointing at the parent.</p>
 *
 * <p>{@code sessionId} is the logical session identity shared by all invocations
 * of one conversation/session. {@code sessionProvenance} records HOW that id was
 * established so a client-declared correlation value is never confused with an
 * authorized server-resolved identity.</p>
 *
 * <p>Types in this package serialize to JSON through explicit {@code ObjectNode}
 * builders (see {@code toJsonNode}) rather than reflection-based bean mapping to
 * remain GraalVM native-image friendly.</p>
 */
public record ToolInvocationContext(
        String invocationId,
        String sessionId,
        String sessionProvenance,
        String parentInvocationId,
        String clientRequestId,
        String taskRef,
        String serverInstanceId,
        String requestedToolName,
        String resolvedToolName,
        String agentName,
        String source,
        long startedEpochMs) {

    /** Client supplied the session id; correlation only, never authorization. */
    public static final String PROVENANCE_CLIENT_DECLARED = "client-declared";
    /** Resolved from the host transcript id (KOMPILE_TRANSCRIPT_UUID or equivalent). */
    public static final String PROVENANCE_TRANSCRIPT_RESOLVED = "transcript-resolved";
    /** Generated by the service; NOT a host conversation id and must never silently merge them. */
    public static final String PROVENANCE_SERVICE_GENERATED = "service-generated";

    public ToolInvocationContext {
        if (invocationId == null || invocationId.isBlank()) {
            throw new IllegalArgumentException("invocationId is required");
        }
        if (sessionId == null || sessionId.isBlank()) {
            throw new IllegalArgumentException("sessionId is required");
        }
        if (startedEpochMs <= 0) {
            throw new IllegalArgumentException("startedEpochMs must be positive");
        }
    }

    public static String newInvocationId() {
        return "inv-" + java.util.UUID.randomUUID();
    }

    public static String newServerInstanceId() {
        return "srv-" + java.util.UUID.randomUUID();
    }

    /** Copy with a new child invocation id, preserving session and parent correlation. */
    public ToolInvocationContext newChild(String childToolName, long startedEpochMs) {
        return new ToolInvocationContext(
                ToolInvocationContext.newInvocationId(),
                sessionId,
                sessionProvenance,
                this.invocationId,
                clientRequestId,
                taskRef,
                serverInstanceId,
                childToolName,
                childToolName,
                agentName,
                source,
                startedEpochMs);
    }

    /** Explicit JSON projection (native-image safe: no reflection). */
    public com.fasterxml.jackson.databind.node.ObjectNode toJsonNode(
            com.fasterxml.jackson.databind.ObjectMapper mapper) {
        var node = mapper.createObjectNode();
        node.put("invocationId", invocationId);
        node.put("sessionId", sessionId);
        node.put("sessionProvenance", sessionProvenance);
        if (parentInvocationId != null) node.put("parentInvocationId", parentInvocationId);
        if (clientRequestId != null) node.put("clientRequestId", clientRequestId);
        if (taskRef != null) node.put("taskRef", taskRef);
        if (serverInstanceId != null) node.put("serverInstanceId", serverInstanceId);
        node.put("requestedToolName", requestedToolName);
        node.put("resolvedToolName", resolvedToolName);
        if (agentName != null) node.put("agentName", agentName);
        if (source != null) node.put("source", source);
        node.put("startedEpochMs", startedEpochMs);
        return node;
    }
}
